### ISSUE TITLE
Bash CLI completion script?

### ISSUE THREAD

**Issue by flipperbw** [sharkdp/bat#1010]
Unless I'm missing something obvious, is there any autocomplete script for bash? I see one for fish, but couldn't find anything for bash.

I can take a pass at converting that one or writing my own, but wanted to check in first.

**Comment by sharkdp** [comment]
We used to have automatically created shell completion files for Bash, Zsh, Fish and PowerShell. They were causing some problems though:
https://github.com/sharkdp/bat/blob/7e844774085f3ecd10182daea9a0122ee008bb82/build.rs#L1-L2

We have since included manually created Fish completion files (https://github.com/sharkdp/bat/issues/372)

Apart from the reasons given in https://github.com/sharkdp/bat/pull/524#issuecomment-480018300 I am open to including manually created shell completion files.

As a starting point, you could either take the Fish completion file (which is probably already out of date) or re-enable the automatic generation of completion files and manually fix the autogenerated Bash completion file.

**Comment by flipperbw** [comment]
Hmm gotcha. I will take a look.

**Comment by flipperbw** [comment]
What I wound up doing, in lieu of making a whole script, was just to add the line `complete -F _longopt bat` to my profile. It's not perfect but it's a quick and easy fix for some completion without the need for an entire file.

**Comment by ernstki** [comment]
@flipperbw That's a great idea, and not a thing I even knew existed. Now I can stop re-inventing the wheel of parsing the output of a command's `--help` into a word list for `complete -W`. <tt>:)</tt>

Worth noting, though, that that's [part of bash-completion](https://github.com/scop/bash-completion/blob/0c69125d65faaa60b0829db58c88dc33366bb67c/bash_completion#L1969), which is often a separate package for people to install / set up.

**Comment by bretty-mcbrettface** [comment]
True, though I suppose it could be tested for in an install script here, and if not, include that function definition.

**Comment by flipperbw** [comment]
True, though I suppose it could be tested for in an install script here, and if not, include that function definition.

**Comment by sharkdp** [comment]
We now have custom Zsh and Fish completion files. It would be great if someone could write a Bash completion file as well.

**Comment by ds2606** [comment]
Just an FYI, filename completion no longer works using zsh with the re-dded scripts. For example, with directory `~/Misc`, `bat ~/mi<tab>` doesn't expand to the full directory, whereas it does for me with any other completion executable (e.g. `ls ~/mi<tab>` expands to `ls ~/Misc`)

**Comment by scop** [comment]
Is this a case sensitivity thing (`~/mi` vs `~/Misc`), or do you see the problem also when completing `~/Mi<tab>`? I can't check right now but the bash completion implemented in #1678 certainly didn't break the usual case sensitive completions for me. No idea/about zsh.

**Comment by ds2606** [comment]
It's case specific - filename completions for e.g. `~/Mi<tab>` work fine (I'm accustomed by muscle memory to tab through paths case-insensitively though so even if it's minor it's a bit if a dealbreaker usage-wise for me)

**Comment by scop** [comment]
I've just verified that the bash completion from #1678 does *not* break case sensitive nor case insensitive path completions (case insensitive ones are enabled with `set completion-ignore-case on` in e.g. `~/.inputrc` for bash (well readline)).
