### ISSUE TITLE
Performance for line range of large files?

### ISSUE THREAD

**Issue by max-sixty** [sharkdp/bat#1058]
Thanks a lot for bat, it's awesome, I use it every day.

I just tried to use it to display a line range in the middle of a large file. Displaying 10 lines towards the end of the file with a command like `bat -r 100000:100010 $FIILE` took:
- 9m 20s for a 1.9G file
- 1m 10s for a 110M file

sed did the same range for the second file in 650ms

Alternatively let me know if I'm using the wrong command / this is the wrong tool for this sort of task.

**Comment by keith-hall** [comment]
In order to determine how to highlight that range/part of the file, it generally has to parse everything before it. I guess some syntax definitions have no contexts, and for those it would be unnecessary, as previous lines wouldn't affect how later lines get scoped, so could potentially be optimized... What language files are you viewing which are that large?

I think your best bet for now is to get the range you are interested in externally and pipe that to bat.

**Comment by sharkdp** [comment]
> I think your best bet for now is to get the range you are interested in externally and pipe that to bat.

you could actually do that by using two `bat` instances:
```
bat -r 100000:100010 $FIILE | bat -l …
```
The first `bat` will not use syntax highlighting and will be much faster that way.

**Comment by max-sixty** [comment]
> What language files are you viewing which are that large?

I use `bat` as an alias for cat, so in this case I'm looking at CSVs and don't need syntax highlighting.

> you could actually do that by using two bat instances:

OK great, I'll do that, thanks.
