### ISSUE TITLE
nginx conf files

### ISSUE THREAD

**Issue by 58bits** [sharkdp/bat#1107]
**Syntax:**
Nginx conf files

**Guideline Criteria:**
https://packagecontrol.io/packages/nginx

bat is brilliant. thank you!

**Comment by sharkdp** [comment]
Sounds good, thank you!

**Comment by cedric-sun** [comment]
@sharkdp Would appreciate it if Apache httpd.conf is supported as well. :)
Ref: https://httpd.apache.org/docs/trunk/mod/quickreference.html

Just thinking. Is it possible to modularize the syntax system so that syntax rules can be developed separately, and new syntax supports can be added by simply provides a syntax-description file?

Thanks.

**Comment by sharkdp** [comment]
Both should be supported in the next release thanks to changes by @niklasmohrin in #1137.

**Comment by sharkdp** [comment]
Added in [v0.16.0](https://github.com/sharkdp/bat/releases/tag/v0.16.0).
