### ISSUE TITLE
Output the content of grep using bat?

### ISSUE THREAD

**Issue by AeonFr** [sharkdp/bat#1144]
Has anyone managed to concatenate the result of bat with grep? In my test it seems to be fallbacking to cat.

<img width="486" alt="Screenshot 2020-08-18 at 18 47 32" src="https://user-images.githubusercontent.com/11742754/90541680-48689400-e183-11ea-9ae0-26642628cae7.png">

vs.

<img width="512" alt="Screenshot 2020-08-18 at 18 47 58" src="https://user-images.githubusercontent.com/11742754/90541721-56b6b000-e183-11ea-94f9-fa272a165af9.png">

---

Edit: more context/troubleshooting:

- When running the first command, using `bat` or `cat` the result looks the same
- Using `grep --color=always` didn't produce any difference
- I'm not sure if this is even possible or optimal since it would mean formatting the whole file just to output a chunk 🤔

**Comment by sharkdp** [comment]
> When running the first command, using `bat` or `cat` the result looks the same

Yes. This is a feature of `bat`. Whenever you pipe its output to another program or a file, it will fall back to plain `cat` behavior.

> Using `grep --color=always` didn't produce any difference

No, but using `bat --color=always` should result in a difference:

![image](https://user-images.githubusercontent.com/4209276/90547735-41924f00-e18c-11ea-8bfb-58993a8ffcd2.png)

Note that I'm not advocating to use this, as it's likely to produce wrong output. The problem is that `bat` will output ANSI escape sequences for colorization. These can interfere with your search query. Note how this does not work as expected:
``` bash
> bat --color=always package.json | grep -A 8 '"scripts"'
# no output
```

The problem is that there is a color change between the `"` character and the word `script`. Using something like `grep -A 8 '".*scripts.*"'` would work, but require you to know where color changes appear.

That being said, it should work in most cases.

> I'm not sure if this is even possible or optimal since it would mean formatting the whole file just to output a chunk

True, but that's a good thing. If you do not format the whole file, you are likely to run into formatting problems (imagine a HTML-style multiline comment `<!--` somewhere at the beginning of the file). Again - that being said - you can also do it the opposite way:
![image](https://user-images.githubusercontent.com/4209276/90548204-e44acd80-e18c-11ea-8ecb-95092118bc22.png)

This is typically the better choice, since it guarantees that your search is not disrupted by colorization escape sequences. The drawback is that you have to specify the language explicitly. And that the `grep` output might not be valid JSON anymore, leading to incorrect syntax highlighting.

**Comment by AeonFr** [comment]
I now see the complexity of piping commands to the output of `bat`, so I think doing it the other way (piping the result of grep to bat) will go better.

I've noticed in a lot of git diff visualizers, this issue where a comment or an unclosed tag causes incorrect formatting. It's a risk I'd be assuming (for my particular use case it's not a big problem)

BTW the documentation is full of examples of how to pipe `bat` with other commands, but I was too blind to understand the underlying concept. After reading this I think I understand it better:

> `bat` can recieve the output of standard input (via piping `|`) and format it, but the formatting will only be correct if you explicitly define the language via the `-l` option.

(Sorry if this was already documented).

Thanks for the quick reply. Closing this.

**Comment by eth-p** [comment]
@AeonFr, I think you might be able to make use of [batgrep](https://github.com/eth-p/bat-extras/blob/master/doc/batgrep.md). It combines ripgrep and bat together in a way that displays syntax highlighting.

Unfortunately due to some limitations, it's not exactly the fastest tool, but maybe it would work well enough for your needs?

**Comment by AeonFr** [comment]
I will check batgrep.

I'm setting some aliases to access different projects and I always forget the commands for each project, so I simply wanted the alias to `cd` into each project and to print the "scripts" part of the package.json

So high end performance is not really needed for this use case.

Thanks
