### ISSUE TITLE
MANPAGER won't work on Mandoc's man implementation

### ISSUE THREAD

**Issue by Bumbadawg** [sharkdp/bat#1145]
**What version of `bat` are you using?**
0.15.4

**Describe the bug you encountered:**
Using `export MANPAGER="sh -c 'col -bx | bat -l man -p'"`
results in `-bx: 1: Syntax error: Unterminated quoted string`

**Describe what you expected to happen?**
paging with bat

**How did you install `bat`?**
**Void Linux** package manager

** The bug **
It was already reported here for **Termux**, and it coudl well be the case for **Alpine** and other Mandoc's man implementations cases.
See https://github.com/termux/termux-packages/issues/4781#issuecomment-573110911

** Lazy solution **
Instead of recompiling man from GNU (https://www.nongnu.org/man-db/development.html)
one can be using `export MANPAGER='nvim +Man!'`

**Comment by sharkdp** [comment]
Thank you for reporting this.

This is not a bug in `bat`. This implementation of man is currently not supported. This should probably be documented.

**Comment by lahwaacz** [comment]
It does not work because mandoc does not do shell tokenization of the `$MANPAGER` string, it just splits it into a list of words and passes them to `execvp`. So the error comes from `sh` which complains about an unterminated quoted string from the word `'col`.

`bat` itself does not have any problems displaying the output of mandoc's `man` command, you just have to configure the pager appropriately. This can be done by putting the following in a wrapper script and then `export MANPAGER="your_wrapper"`:
```
#!/bin/sh
cat "$1" | col -bx | bat --language man --style plain
```

**Comment by eth-p** [comment]
> ```
> #!/bin/sh
> cat "$1" | col -bx | bat --language man --style plain
> ```

Not that performance matters much for a shell script like this, but you can even cut out the cat invocation:

```shell
col -bx < "$1" | bat --language man -p
```

**Comment by ju1ius** [comment]
> col -bx < "$1" | bat --language man -p

Or:
```sh
#!/bin/sh
exec col -bx | bat -pl man

**Comment by lahwaacz** [comment]
> > col -bx < "$1" | bat --language man -p
> 
> Or:
> 
> ```shell
> #!/bin/sh
> exec col -bx | bat -pl man
> ```

These two commands are *not* equivalent - the former reads from a file denoted by `$1` and the latter reads from stdin. The former is required for mandoc, the latter may be required for other things that use `$MANPAGER` (e.g. using the `help` function in an [ipython](https://ipython.readthedocs.io/en/stable/) shell). The following can be used as a universal solution (until somebody finds an improvement again :stuck_out_tongue:):

```sh
#!/bin/sh

if test "$#" -eq 0; then
    # no CLI arguments - read from stdin
    exec col -bx | bat --language man --style plain --pager "$PAGER"
else
    # mandoc does not write to stdout, it passes a file name
    # https://github.com/sharkdp/bat/issues/1145
    exec col -bx < "$1" | bat --language man --style plain --pager "$PAGER"
fi
```

**Comment by WhyNotHugo** [comment]
@lahwaacz Thanks, this solution works wonderfully!

**Comment by eth-p** [comment]
As part of my investigation into other man-related issues, I figured out why the `mandoc` implementation doesn't work:

It does extremely simple shell splitting for the `MANPAGER` variable, which makes it impossible to escape spaces.

![image](https://github.com/sharkdp/bat/assets/32112321/3f0d0ec9-6928-401b-b022-595b7cd16270)

@lahwaacz's approach of putting it in a separate script is the only solution to having this work with `mandoc`.

**Comment by Mark-Joy** [comment]
> ```shell
> exec cat "$@" | col -bx | bat --language man --style plain --pager "$PAGER"
> ```

Or this for better performance:
```shell
#!/usr/bin/env sh
if [ -f "$1" ]; then
  col -bx < "$1" | bat --language man --plain
else
  col -bx | bat --language man --plain
fi
```

**Comment by lahwaacz** [comment]
> Or this for better performance:

Did you actually measure it?

In any case, `[ -f "$1" ]` seems like a wrong condition: if there is no file but stdin, there is no `$1` itself.

**Comment by Mark-Joy** [comment]
> In any case, `[ -f "$1" ]` seems like a wrong condition: if there is no file but stdin, there is no `$1` itself.

what else is the `else clause` for?
The code means: if the `input` is a `file` then take the file, otherwise take the `stdin`

> Did you actually measure it?

Do I have to? One must be processed through `cat` and then `col`, while the other just goes through `col`

**Comment by lahwaacz** [comment]
> > In any case, `[ -f "$1" ]` seems like a wrong condition: if there is no file but stdin, there is no `$1` itself.
> 
> what else is the `else clause` for? The code means: if the `input` is a `file` then take the file, otherwise take the `stdin`

You should not check if `$1` is a file, but if there is actually any _input_. Find out what `$#` is... :wink: 

> > Did you actually measure it?
> 
> Do I have to? One must be processed through `cat` and then `col`, while the other just goes through `col`

And you have added one shell condition instead. What do you think is faster: `cat` or `[ -f "$1" ]`?

**Comment by Mark-Joy** [comment]
Hey, so you have so much free time in your life huh? 

It just bothered me when you don't understand the code and saying it's wrong. It's not wrong. See, after you figure out what my code means, you already improve it. Good learning for you, right? 😉
I'll take your offer then 
```
#!/bin/sh
if [ $# -eq 0 ]; then
  col -bx | "$BAT_BIN" --language man --plain
else
  col -bx < "$1" | "$BAT_BIN" --language man --plain
fi
```

> And you have added one shell condition instead. What do you think is faster: `cat` or `[ -f "$1" ]`?

Isn't it obvious? But sure, have it your way.. I don't have much time and energy for something like this

**Comment by Mark-Joy** [comment]
You are all the way right 😉

**Comment by meator** [comment]
> ```sh
> #!/bin/sh
> 
> # mandoc passes a file name, other tools write to stdout
> # using `cat "$@"` we take care of both reading from file and stdin
> exec cat "$@" | col -bx | bat --language man --style plain --pager "$PAGER"
> ```

This appears to be the most fleshed-out solution here, so I will comment on it.

The `col` utility [is deprecated](https://pubs.opengroup.org/onlinepubs/7908799/xcu/intro.html#tag_001_003_003) and [harder to come by on musl systems](https://github.com/util-linux/util-linux/blob/v2.41.2/configure.ac#L2326) ([WhyNotHugo above](https://github.com/sharkdp/bat/issues/1145#issuecomment-1406697952) has mentioned that `col` is also provided by `heirloom-doctools`, but my distro doesn't seem to package it + it doesn't change the fact that `col` is deprecated).

Here are some alternatives I've come up with:

```sh
#!/bin/sh

# mandoc passes a file name, other tools write to stdout
# using `cat "$@"` we take care of both reading from file and stdin
exec cat "$@" | expand | sed 's/.\x08//g' | bat --language man --style plain
```

if you want to do all processing in a single command:

```sh
#!/bin/sh

# mandoc passes a file name, other tools write to stdout
# using `cat "$@"` we take care of both reading from file and stdin
exec cat "$@" | sed -e 's/.\x08//g' -e 's/\t/    /g' | bat --language man --style plain
```

I don't know how `col` decides the width of a tab (is it pulling it from terminfo like the `tabs` program? is it hardcoded to 8?). I would trust my first script more. I wasn't able to test tab behavior much, because my mdocml doesn't seem to output many tabs (but I'm not a manpage wizard).

If you've got suggestions on improving my solution, please comment on it here.
