### ISSUE TITLE
system-wide config dir

### ISSUE THREAD

**Issue by rsteube** [sharkdp/bat#1264]
would be nice to have a system-wide config dir so that [customizations](https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions) can provided using the system package manager (e.g. bat-syntax-sig)

related #948

**Comment by sharkdp** [comment]
Please see #668

**Comment by Mixaz017** [comment]
I understand this is an old issue, but I believe it wasn’t a duplicate. As far as I can tell, #1888 only added support for the configuration file, not for syntaxes or themes. This issue was closed as a duplicate, even though the requested feature wasn’t addressed in #1888.

Adding support for system-wide syntaxes and themes would allow custom syntaxes and themes to be packaged and shared through repositories like AUR (which is exactly what I was trying to do). I would greatly appreciate it if this feature could be implemented in bat.
