### ISSUE TITLE
Installation with rust 1.20.0 fails

### ISSUE THREAD

**Issue by kBite** [sharkdp/bat#14]
I tried to install bat with `cargo`, but got some error[E0277] messages. After updating to lastest version installation works fine.

Is this a bug or is expecting / using latest rust version a default for rust software I wasn't aware of?

```
# failing
$ cargo -V
cargo 0.21.0 (5b4b8b2ae 2017-08-12)

$ rustc --version
rustc 1.20.0 (f3d6973f4 2017-08-27)
```
```
# successfull
$ cargo -V
cargo 0.26.0 (41480f5cc 2018-02-26)

$ rustc --version
rustc 1.25.0 (84203cac6 2018-03-25)
```

---
Example error message for reference purpose
```
$ cargo install bat
[ ... ]
error[E0277]: the trait bound `std::option::Option<std::collections::HashMap<u32, LineChange>>: std::ops::Try` is not satisfied
   --> /home/kbite/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.1.0/src/main.rs:120:16
    |
120 |        let diff = repo.diff_index_to_workdir(None, Some(&mut diff_options))
    |   ________________-
    |  |________________|
    | ||
121 | ||         .ok()?;
    | ||              -
    | ||______________|
    | |_______________the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                 in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<std::collections::HashMap<u32, LineChange>>`
    = note: required by `std::ops::Try::from_error`

error: aborting due to 5 previous errors

error: failed to compile `bat v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-install.1dfJ32nRGNx6`

Caused by:
  Could not compile `bat`.
```

**Comment by sharkdp** [comment]
> I tried to install bat with cargo, but got some error[E0277] messages.

Thank you for the feedback. I'm using the `?` operator for the `Option<..>` type, which has been a really useful feature when implementing bat. This feature has been enabled in Rust 1.22 (2017-11-22).

Unless there are any strong reasons to backport it to a previous version of rust, 1.22 is going to be our minimal supported version of Rust so far. I'm going to add a comment to the install section in the README.

> Is this a bug or is expecting / using latest rust version a default for rust software I wasn't aware of?

This is no a "default" behaviour, but since this is just a small fun project (so far), I don't see any benefit in restricting myself to an older standard of the Rust language.

**Comment by sharkdp** [comment]
Also, I'm using Travis to check that the minimum required rust version is still supported:
https://github.com/sharkdp/bat/blob/716b261efdc25073f8352e52e239d19d206f4377/.travis.yml#L13-L19
