### ISSUE TITLE
Bad handling of pseudo files

### ISSUE THREAD

**Issue by x4e** [sharkdp/bat#1425]
**What version of `bat` are you using?**
0.16.0

**Describe the bug you encountered:**
Pseudo files such as /dev/random are not properly displayed. On the first attempt to view them, an empty file will be displayed. Only on the second attempt will it display the output from the first attempt.

**What did you expect to happen instead?**
Pseudo files should be correctly handled as having dynamic contents which must be continually queried and displayed.

**How did you install `bat`?**
Pacman

---

```
system
------

**$ uname -srm**
Linux 5.9.8-arch1-1 x86_64

**$ lsb_release -a**
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

bat
---

**$ bat --version**
bat 0.16.0

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

**$ /bin/zsh --login -i -c type cat**
cat is an alias for bat

tool
----

**$ less --version**
less 563 (PCRE regular expressions)
```

**Comment by sharkdp** [comment]
>  Pseudo files such as /dev/random are not properly displayed. On the first attempt to view them, an empty file will be displayed. Only on the second attempt will it display the output from the first attempt.

They are handled just fine. The problem is that `bat` reads a full line until it prints something to stdout. And if we invoke a pager, we wait for a full screen height to fill. So it does not depend on the first run or the second run. It's pure luck. Whether you receive enough newline `\n` characters until you give up, or not. If you wait long enough, you should eventually see some output.

To see this, try running `bat` without a pager and maybe use the `-A`/`--show-all` option (to see something useful). Also, try `/dev/urandom`, which is typically faster
```
bat --paging=never --show-all /dev/urandom
```

**Comment by x4e** [comment]
I see, that makes a lot of sense, thanks for clearing that up. Bat already wraps long lines, so perhaps it should start printing a line once it has reached the wrapping distance?

**Comment by sharkdp** [comment]
Yes - see #636 and #712.

**Comment by x4e** [comment]
Thanks, thats great!
