### ISSUE TITLE
How can I make the color palettes of the bat command nicer? Currently it is like cat itself

### ISSUE THREAD

**Issue by monajalal** [sharkdp/bat#1448]
![Screenshot from 2020-12-24 17-21-17](https://user-images.githubusercontent.com/1892917/103107464-86cbff00-460c-11eb-8a81-c05fb792f5cd.png)

**Comment by atharvadnaik** [comment]
Initially txt file look like this
![bat-#1448-1](https://user-images.githubusercontent.com/50011593/103125522-568a6c00-46b1-11eb-88d4-b172996dd547.jpg)

1. Generate bat config file using: 
$ bat --generate-config-file
2. locate bat config file using:
$ bat --config-file
3. open it in your text editor and add following line:
--map-syntax "*.txt:Python" (or your favorite syntax instead of Python... You can list them using $ bat --list-languages)

Now it will look like this:
![bat-#1448-2](https://user-images.githubusercontent.com/50011593/103125692-eaf4ce80-46b1-11eb-9833-bbed59b0283d.jpg)

**Comment by j0hnmeow** [comment]
> ![Screenshot from 2020-12-24 17-21-17](https://user-images.githubusercontent.com/1892917/103107464-86cbff00-460c-11eb-8a81-c05fb792f5cd.png)

The reason is that `bat` doesn't know how to highlight it - is it Java, CoffeeScript, Haskell, Python, YAML or something else? It knows how to highlight `requirements.txt`, but not `requirements_DJR.txt`. So we should say "Treat `requirements_DJR.txt` like it is `requirements.txt`". This can be done with [`--map-syntax`](https://github.com/sharkdp/bat#adding-or-changing-file-type-associations) option - we want to highlight any file starting with `requirements` and ending with `.txt`, so the setting is `--map-syntax "requirements*.txt:requirements.txt"`. It is better to specify it in the [config file](https://github.com/sharkdp/bat#configuration-file), like @atharvadnaik said. 
So, the complete solution is:
```sh
bat --generate-config-file # If you don't have a config file
echo '--map-syntax "requirements*.txt:requirements.txt"' >> $(bat --config-file) # If you use fish shell, remove the $ symbol
```

**Comment by monacv** [comment]
@j0hnmeow confirming that it worked
Thanks a lot
![Screenshot from 2020-12-29 14-54-06](https://user-images.githubusercontent.com/76495162/103310502-c1a3ad80-49e5-11eb-8418-9fe7f8740e73.png)
