### ISSUE TITLE
why this .sh file output is not shown in colors?

### ISSUE THREAD

**Issue by monacv** [sharkdp/bat#1456]
![Screenshot from 2020-12-29 14-46-56](https://user-images.githubusercontent.com/76495162/103310072-b56b2080-49e4-11eb-8f91-45993faf53f7.png)

```

[11741:3298 0:1063] 02:46:00 Tue Dec 29 [mona@goku:pts/1 +1] ~
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
11656/31772MB




[11741:3298 0:1069] 02:48:50 Tue Dec 29 [mona@goku:pts/1 +1] ~
$ aptitude versions bat
Package bat:                              
p   0.12.1-1build1 
```

**Comment by keith-hall** [comment]
Thanks for reporting. Presumably this is because the `.sh` file extension is recognised as a bash script, and it doesn't check the shebang line to see it's using a python interpreter. Have you considered renaming the file to have a `.py` extension instead?
Potentially related is the discussion at https://github.com/sharkdp/bat/issues/1262#issuecomment-704547094

**Comment by keith-hall** [comment]
Also related : https://github.com/sharkdp/bat/issues/685#issuecomment-563211780
