### ISSUE TITLE
Directories on macOS

### ISSUE THREAD

**Issue by ahti** [sharkdp/bat#151]
On macOS, config files (themes, syntaxes) currently need to be placed in `~/Library/Preferences/bat`.  While this is where macOS GUI applications store their preferences, I have not seen many (or any? I'm not sure) command line tools that use `~/Library/Preferences`. Looking at my home folder, cli tools seem to, generally, use either dotfiles in home or `~/.config`.

I'd prefer if bat searched for config files in `~/.config/bat` on macOS just like on Linux. While it may not be the "correct" way to choose directories on macOS, it seems to be convention and would make things like sharing a dotfiles repo between Linux and macOS much more convenient.

**Comment by ghuls** [comment]
@ahti 
Probably the reason why most CLI tools store there settings in ~/.config is because they are ported from Linux/BSD and follow XDG Base Directory Specification: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I don't know if directories supports it or not, but it theoretically could support XDG paths when you set all those XDG variables on MacOS.

For now, just make a symlink:
```
ln -s ../Library/Preferences/bat ~/.config/bat
```

**Comment by sharkdp** [comment]
I'm going to close this ticket for now, as it seems to me that (1) we are actually following the standard guidelines for macOS and (2) there is an easy workaround.

I'm happy to re-open this ticket if there is a strong support to change this.
