### ISSUE TITLE
Language formatting

### ISSUE THREAD

**Issue by gomeology** [sharkdp/bat#1592]
Is it possible to have the output formatted in a more readable format. example in the images below
![unformatted](https://user-images.githubusercontent.com/36292577/111782684-b39c5500-888f-11eb-8f68-8a6945d4c4ab.PNG)
![formatted](https://user-images.githubusercontent.com/36292577/111783265-6a98d080-8890-11eb-8205-9a523f605c19.png)

**Comment by keith-hall** [comment]
Thanks for the request. I personally think reformatting is out of scope for bat, partially because its billed as a cat replacement with syntax highlighting and other optional features. Thus it typically shows files exactly as they appear on disk, just with color and line numbers etc.

I don't know of any way to easily pretty print any type of file, (which would thus be another thing to maintain) but for your concrete use case you could use `jq` and pipe the output into bat. You could also make a shell alias if its something you want to do often / by default :)

**Comment by Enselic** [comment]
Just wanted to chime in with a JSON formatting tip. I personally prefer `python3 -m json.tool` over tools such as e.g. `jq` since the former is usually installed by default on most systems. Combined with `bat` it would look like this (with colors in a real terminal, of course):

```
% echo '{"format":"me", "please": true}' | python3 -m json.tool | bat -l json
───────┬────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────
   1   │ {
   2   │     "format": "me",
   3   │     "please": true
   4   │ }
───────┴────────────────────────────────────────────────────
```

**Comment by sharkdp** [comment]
Please check out `prettybat` in https://github.com/eth-p/bat-extras
