### ISSUE TITLE
typos in 'apt show bat' document

### ISSUE THREAD

**Issue by hobbsy** [sharkdp/bat#1613]
Hello,

(I'm not sure where this file is located so I'm not sure where/how to submit a Pull Request)

If you type `apt show bat` in a Ubuntu system, in the document displayed on screen it has a couple of typos:

` In this package the executable and its manpage have been renamed from ‘bat’ to
  ‘**batbat**’ because of a file name clash with another Debian **paclage**.`

I think 'batbat' should be 'batcat' and 'paclage' should be 'package'

**Comment by hobbsy** [comment]
sorry I notice this has already been reported:
https://github.com/sharkdp/bat/issues/1079
https://github.com/sharkdp/bat/issues/982#issuecomment-627383547

but issue still persists (?)


( @paride )

**Comment by paride** [comment]
Hi @hobbsy,

Mostly fiy: this is not really an "upstream" bat bug, but an Ubuntu bug which belongs to the Ubuntu bug tracker: https://launchpad.net/ubuntu/+source/rust-bat/+bugs.

Anyway this is fixed already in Ubuntu, but releasing the fix to Focal requires following the SRU process (https://wiki.ubuntu.com/StableReleaseUpdates), and this bug alone doesn't qualify. I could try to piggy-back the fix for this on top of https://launchpad.net/ubuntu/+source/rust-bat/+bugs if I'll ever find the time to fix that one.

I think you can close this issue. I you want to follow (or help with) progress on the typos bug (which admittedly are due to my fat fingers) the right bug report is https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1897610.

**Comment by hobbsy** [comment]
thanks for the response @paride
