### ISSUE TITLE
Terminal needs `reset` if used with `fzf`

### ISSUE THREAD

**Issue by edwardsnjd** [sharkdp/bat#1650]
Thanks for this fantastic tool.  This is a minor bug observed when using `bat` in a pipeline after `fzf`.

**Describe the bug you encountered:**

Piping the output of an interactive `fzf` session into `bat` leaves the terminal in a slightly broken state.

After the pipeline completes the terminal has a hanging indent and no longer echos keystrokes.   (`reset` fixes the terminal.)

A minimal example:
```sh
$ echo foo | fzf | bat
# ... terminal is now unhappy
```

With annotations for the interactions:
```sh
$ echo foo | fzf | bat
# fzf opens as expected
# pressing enter selects "foo" as expected
# bat formats "foo" from stdin as expected
───────┬─────────────────────────────────────
       │ STDIN
───────┼─────────────────────────────────────
   1   │ foo
───────┴─────────────────────────────────────
        $ # <-- BUG: prompt indented and keys aren't echoed
```

Examples that don't show the bug:
```sh
$ echo foo | fzf
foo
$ echo foo | fzf | cat
foo
$ echo foo | fzf | less
foo
```

Examples that also show the bug:
```sh
$ echo foo | fzf | cat | bat
# ...
```

*PS1 changes the behaviour*

Changing my bash prompt changes the way the state the terminal is left in.

Setting the prompt to "Hi $", the echo is still not working but there is no indent:

```sh
$ PS1="Hi $ "
Hi $ echo foo | fzf | bat
───────┬──────────────────────────────────────
       │ STDIN
───────┼──────────────────────────────────────
   1   │ foo
───────┴──────────────────────────────────────
Hi $ # <-- BUG:No echo, no newlines on "return" but no hanging indent
```

Including a newline in the bash prompt reintroduces the hanging indent:

```sh
$ PS1="Hi \012$ "
Hi
$ echo foo | fzf | bat
───────┬─────────────────────────────────────────
       │ STDIN
───────┼─────────────────────────────────────────
   1   │ foo
───────┴─────────────────────────────────────────
Hi
Hi $ # <-- BUG: Hanging indent, no echo
Hi $ # <-- BUG: Hanging indent, no echo
   $ # <-- BUG: Hanging indent, no echo
```

**What did you expect to happen instead?**

I expected the terminal to be left in the state it started in.

**How did you install `bat`?**

homebrew

**bat version and environment**

#### Software version

bat 0.18.1 (<no git>)

#### Operating system

macOS 11.3 (Darwin 20.4.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/usr/local/bin/bash
PAGER=<not set>
LESS='--quit-if-one-screen --RAW-CONTROL-CHARS --no-init'
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

```

```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

#### Terminal emulators

This bug occurs in `iTerm2`, `Terminal.app` and `Alacritty`.

**Comment by sharkdp** [comment]
Thank you for reporting this. I can reproduce it. It does work with `bat --paging=never`.

More out of curiosity... could you please describe your use case?


possibly related: #1585

**Comment by Enselic** [comment]
I can reproduce it with `bat`, but I can also reproduce it with just `less`, using your example command. I do like this:

1. Run `echo foo | fzf | less`
2. I now get presented with a list of just one item, namely `foo`, so I just press Return on my keyboard to select it
3. That makes `fzf` exit, but I am still within `less`, so I press `q` and Return to quit `less` (that I have to also press Return is an indication of that the terminal mode is messed up already)

After doing 3, my terminal is messed up, just like when using `bat`. So this does not seem to be a `bat` bug. *Sometimes* the terminal mode is not messed up, but most of the times it is, using the above step-by-step. So we have a race condition at hand.

`fzf` is changing terminal mode to support its UI. `less` also change terminal mode to supports *its* UI. And since terminal mode is a shared resource, it is easy to end up in the wrong state due to race conditions. For a deep dive into this problem in the scope of another bug I recommend you to read [this comment](https://github.com/sharkdp/bat/issues/1006#issuecomment-742034888).

Am I the only one that can reproduce with just `less`?

Btw, you can see why your terminal is messed up, by running `stty`. For example, in the messed up state, I can see that `-opost` is active. That means "postprocess output disabled", which in turn means that the terminal does not automatically insert a `\r` after a `\n`. You can manually enter this terminal mode by running `stty -opost`.

**Comment by sharkdp** [comment]
@Enselic Great analysis!

I did previously try to reproduce it with plain `less`, but could not. I didn't think of a race condition, so I did not repeat the sequence.

I now tried it for like 20 times and still couldn't reproduce it. I then ran `stress --cpu 8` in the background and was immediately able to reproduce the bug with just `less`.

**Comment by edwardsnjd** [comment]
@sharkdp Yes, #1585 sounds very similar to me.

@Enselic Thank you for that great write up.  And yes, your comment on #1006 was enlightening!

I now see the difficulty in running multiple tools that change the terminal input mode in a single pipeline.  With that context, I don't consider my reported behaviour a bug (in either `fzf` or `bat`) because it seems to me that asking two rich tools to share the terminal is probably unwise.  My particular use case is easily solved by splitting the pipeline into two separate commands.

Just for reference, what I was trying to do was build a little bash function to interactively choose a git version of a file to view.  In pseudo code It looked something like this:
```sh
function file_history {
  list_commits $1  \
    | fzf --preview="summarize_commit {}" \
    | show_file_commit $1 \
    | bat --file-name=$1
}
```

I'll solve my case by splitting the pipeline into two so only one owns the terminal at a time:
```sh
function file_history {
  sha=$(
  list_commits $1  \
    | fzf --preview="summarize_commit {}"
  )
  echo $sha \
    | show_file_commit $1
    | bat --file-name=$1
}
``` 

([Actual script in my dot files](https://github.com/edwardsnjd/dot-files/commit/3f4586a3119094bdefe14fed92a483ec8bcd37f6))
