### ISSUE TITLE
Theme Dark+ VS Code not showing up after BAT upgrade to 0.18.1

### ISSUE THREAD

**Issue by ciscohack** [sharkdp/bat#1651]
Hi Team,

I upgrade the BAT to 0.18.1 on macOS BigSur version 11.3.1 code and as per release note. in 0.18.1 code new theme Dark+ VS code added. But when i ran command BAT --list-themes. it's not showing up. Do i need system restart after upgrade to show up the theme or need any other changes to make it work.

Bat -V
bat 0.18.1

 OS: macOS 11.3.1 20E241 x86_64
 Host: MacBookPro16,1
 Kernel: 20.4.0

-Praveen

**Comment by sharkdp** [comment]
Can you please post the output of `bat --diagnostic`? Do you maybe have a custom set of syntaxes/themes? In that case, you might need to re-create this with `bat --build` or clear it with `bat --clear`.

**Comment by ciscohack** [comment]
> bat --diagnostic

><((("> bat --diagnostic
#### Software version

bat 0.18.1 (<no git>)

#### Operating system

macOS 11.3.1 (Darwin 20.4.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=' -R -X -F -i '
BAT_PAGER='less -iRXF --incsearch'
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=base16-256
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### Config file

```
# This is `bat`s configuration file. Each line either contains a comment or
# a command-line option that you want to pass to `bat` by default. You can
# run `bat --help` to get a list of all possible configuration options.

# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
#--theme="Sublime Snazzy"

# Enable this to use italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default):
#--italic-text=always

# Uncomment the following line to disable automatic paging:
#--paging=never

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
#--pager="--RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#   Example 1: use the C++ syntax for .ino files
#   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
#--map-syntax "*.ino:C++"
#--map-syntax ".ignore:Git Ignore"
#--map-syntax "*.txt:Python"
#--map-syntax "*.log:Python"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 581.2 (PCRE regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less

**Comment by ciscohack** [comment]
> bat --clear

Bat --clear do i need to pass any argument with this. In man page i can't see clear also. not working for me. Hope we find a way to fix this theme issue without rebuilding

**Comment by sharkdp** [comment]
Sorry, I meant `bat cache --clear`.

**Comment by sharkdp** [comment]
Unrelated to this ticket:

> bat 0.18.1 ()
@Enselic: do you know how this can happen (not Git hash information)?

Also, we should add a custom `bugreport` collector that tells us about whether or not a user has built a custom cache.

**Comment by ciscohack** [comment]
> Sorry, I meant `bat cache --clear`.

Thanks but this well clear my compiled theme. not optimal choice anyway this fix the problem.

**Comment by sharkdp** [comment]
In that case, please try `bat cache --build`, as suggested above.

**Comment by ciscohack** [comment]
> In that case, please try `bat cache --build`, as suggested above.

yes i did very same when you last time asked to run bat cache --clear ( this clear all customer theme and i got Dark+ VS theme) them i rebuild my old theme with bat cache --build. Thanks. But can avoid this in future if we add new themes. we should not do this step again and again. Thanks issue resolved so far. Thanks for your assistance

**Comment by sharkdp** [comment]
We actually have a feature in bat that detects a new major version of bat (e.g. 0.19.x, once it comes out). In that case, `bat` asks you to run `bat cache --build` as it detects that the syntaxes/themes are not compatible.

For 0.18.1, the syntaxes/themes are not "incompatible", so we don't ask users to update it necessarily. But if you want the latest themes in addition to your custom ones, there is no other way than to run `bat cache --build` manually.

**Comment by Enselic** [comment]
> @Enselic: do you know how this can happen (not Git hash information)?

@sharkdp The current git hash implementation in bugreport requires a git repo to be available at build time in order for it to figure out the git hash. Personally I think this is fine, because if someone is *not* building from git (e.g. `cargo install bat` or `brew install bat`), they are generally building an official release, in which case the version information alone is accurate.

The main use case I had in mind for including the git hash in the binary was for people who build from git. Because if you do, the version number alone is insufficient.


It should be possible to make build.rs emit a file with git hash information that is included in published crates and source tarballs, so that bugreport can report an accurate git hash also when building outside of git. But I’m not sure it’s worth the effort.

In any case, we should probably silently skip git hash information if it is missing. Right now we say `(<not set>)` which GitHub apparently sanitize to just `()`, which is not very elegant. I can create a PR for that somewhat soon.

**Comment by sharkdp** [comment]
@Enselic Sorry - my question was unclear. I'm aware that it only works in a Git repository, and that there might be cases where we can not obtain a Git hash. That's perfectly fine. I was only referring to the empty parens ` ()` string. I thought that The parens would be dropped due to

https://github.com/sharkdp/bugreport/blob/0f0983e6a285e0864f1dba2f328772ab2df4f605/src/collector.rs#L62-L65

**Comment by sharkdp** [comment]
I think we can close this for now. Availability of new themes will require users to run `bat cache --build`.
