### ISSUE TITLE
Packaging: Arch Linux

### ISSUE THREAD

**Issue by Johnstone-Tech** [sharkdp/bat#167]
Bat is now in official arch repos, https://www.archlinux.org/packages/community/x86_64/bat/

**Comment by vkobel** [comment]
Well, it's good, but we should have a way to install it using the AUR for more up to date version, or waiting for other repo to sync (manjaro, antergos...).

**Comment by vkobel** [comment]
made one here: https://aur.archlinux.org/packages/bat-cat-git/

**Comment by sharkdp** [comment]
@Johnstone-Tech Awesome! Thank you for the feedback.

@vkobel Thank you! You should probably use `cargo build --release` instead of `cargo build` and install the binary from `target/release/..`. Otherwise, you'll get a debug build which will be much slower.

I'm leaving this ticket open until we have updated the instructions in the README.

**Comment by vkobel** [comment]
@sharkdp Right, forgot about that sorry. AUR package has been updated!

**Comment by sharkdp** [comment]
closed via #170
