### ISSUE TITLE
Escape Sequences get partially stripped

### ISSUE THREAD

**Issue by h4emp3** [sharkdp/bat#182]
Command to reproduce: `echo -e '\033[1;3mfoo\033[22m bar\033[23m baz' | bat`.
Expected output: _**foo**_ _bar_ baz
Actual output: _**foo**_ bar baz

Note that `bar` should be still italic, but it is not when piped through bat. I cannot reproduce this behaviour with other pagers (less, most) or any other shell utility for that matter.

**Comment by sharkdp** [comment]
Thank you very much for reporting this.

**Comment by sharkdp** [comment]
@eth-p Just in case you have time to look at this: could this be caused by the `console::AnsiCodeIterator`?

**Comment by eth-p** [comment]
This is a difficult case to handle. The current implementation will only copy the previously-encountered escape sequence, which ends up stripping any others that came before it. The escape sequence can't just be sent through directly, because the sidebar/panel will end up overriding some of the escape sequences anyways (e.g. color).

The only alternatives I can think of are:

1. Blindly add **every** encountered escape sequence to a buffer and copy it all over on every line. This would work perfectly with SGR (color/style) sequences, but cause major issues with other sequences that move the cursor or alter some terminal setting that depends on the cursor position.

2. Attempt to track the SGR codes, and reproduce them on every line. This adds a fair amount of complexity (and probably missing functionality), though.

**Comment by sharkdp** [comment]
@h4emp3 Just for the record, this is related to character-level wrapping. The bug does not appear when using `bat --wrap=never`.

@eth-p Thank you for the analysis!

**Comment by eth-p** [comment]
@sharkdp I made a pull request for a partial (hacky?) fix as described above.

**Comment by h4emp3** [comment]
Kudos for the quick action you guys took!

Is it not possible to actually track the state for at least the text styling sequences (italic, bold etc)?
I'm not quite certain what is involved in this particular case, but if enough abstractions for different terminals etc are already in place, it should not be too much of a nightmare to do that I guess...

**Comment by sharkdp** [comment]
@h4emp3 This is pretty much what @eth-p does in #185.

**Comment by sharkdp** [comment]
Fix released in [bat 0.5](https://github.com/sharkdp/bat/releases/tag/v0.5.0).
