### ISSUE TITLE
Not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by mbeorlegui** [sharkdp/bat#1840]
```console
$ sudo apt-get install bat
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bat
```

How can I do to make it work?

**Comment by farhansadik** [comment]
You can install it using `wget` from https://github.com/sharkdp/bat/releases

**Comment by MahdyMirzade** [comment]
The `bat` package is available in official ubuntu repositories since Ubuntu 20.* (focal).

This package is not available on **Ubuntu18.04 (Bionic)**, you may need to download `.deb` [(From Here)](https://github.com/sharkdp/bat/releases) files to install it or compile it.

- Ubuntu 18 (bionic) search query: [Click Here](https://packages.ubuntu.com/search?keywords=bat&searchon=names&suite=bionic&section=all)
- Ubuntu 20 (focal) search query: [Click Here](https://packages.ubuntu.com/search?keywords=bat&searchon=names&suite=focal&section=all)

**Comment by mbeorlegui** [comment]
Thanks for the advice!
