### ISSUE TITLE
Why does bat not have ansi as default theme?

### ISSUE THREAD

**Issue by chtenb** [sharkdp/bat#1928]
It's not clear from the readme what the default theme is, but it doesn't look great on all terminals/terminal themes. The README does mention the great benefits of the ansi theme however:

> - Enjoy maximum compatibility. Some terminal utilities do not support more than 3-bit colors.
> - Adapt to terminal theme changes. Even for already printed output.
> - Visually harmonize better with other terminal software.

Maximum compatibility, works great with any setup by default. Why not have the ansi theme as default? That would save a lot of people research time into configuring bat. Most people are just looking for something easy that looks great immediately.

**Comment by Enselic** [comment]
The problem with having ansi as the default theme is that it is much uglier than the default 24-bit theme. And like you say, most users just want something that looks great immediately. The ansi theme does not look great.

Also see https://github.com/sharkdp/bat/issues/1104#issuecomment-663986746

**Comment by chtenb** [comment]
The ansi theme simply uses the base 16 color palette provided by the terminal emulator (i.e. the terminal theme), which is by no means restricted to 256 colors definition. It *does* look good on all my VSCode terminal themes. But thanks for the link. It seems this discussion has been done already.

**Comment by Enselic** [comment]
Most users don't have a carefully selected theme. Compare our current default with ansi on a vanilla system and you'll see that our current default looks much better.

**Comment by fregante** [comment]
> our current default looks much better.

I fail to see how displaying white text on why background is better. macOS has always had a white terminal by default so **by default** bat is broken there. It literally “does not work.” I don’t understand how you can continue to suggest that this is a good default.

**Comment by Enselic** [comment]
I agree we have a problem. The mere fact that we repeatedly get complaints is a good indication of that. Personally, I think it would make sense to do the following:
1. If on macOS, and
2. if no explicit theme is set, and
3. If not `defaults read -globalDomain AppleInterfaceStyle` is `Dark` (see https://github.com/sharkdp/bat/issues/1746)

Then we should default to a theme that looks good on a light background.

It is not a perfect solution, but:
1. It makes us look good on the vast majority of macOS systems
2. The increased startup time can be fixed by explicitly setting a theme

**Comment by Enselic** [comment]
I created a PR to try the above approach. See https://github.com/sharkdp/bat/issues/1746#issuecomment-1133667425.
