### ISSUE TITLE
Use splice?

### ISSUE THREAD

**Issue by rivertam** [sharkdp/bat#194]
This probably doesn't really matter much for the project's goals, but [this blog post](https://matthias-endler.de/2018/fastcat/) details a way to use Linux's `splice` to achieve performance significantly faster than GNU `cat` when actually concatenating files. I don't know if it will benefit `bat` when outputting anything formatted, but for the usecase `cat` is originally for, it would make `bat` better than `cat`.

**Comment by sharkdp** [comment]
Thank you for the feedback and for the reference!

I think we will eventually have two modes within `bat`:

* the standard mode that is already implemented which passes the input through the syntax highlighter, character-level wrapping, adds style elements etc.
* a pass-through mode which simply copies from input to output (just like `cat`)

The second mode will be used if one of these conditions is true:

- one of the inputs is binary (see #150 and #134)
- the output is a non-interactive terminal (a pipe or a file)

I think the `splice`-version could potentially be used for the pass-through mode (on systems that support it). On the other hand, as the author notes, this is probably not really too relevant (if the generic implementation is reasonably fast) because the bottleneck is usually not the speed of `cat`.

**Comment by sharkdp** [comment]
I'm going to close this for now, as I don't see this happening in the close future. Nevertheless, thank you very much for the reference.
