### ISSUE TITLE
golang highlight inside markdown

### ISSUE THREAD

**Issue by laoshaw** [sharkdp/bat#1950]
when markdown contains code blocks they're nicely syntax-highlighted

but when I have go code block they're not highlighted, can we add them?

```
` ` `go
my golang code
` ` `
```

**Comment by sharkdp** [comment]
It should work if you use `golang` instead:

https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/Markdown/Markdown.sublime-syntax#L1230

It looks like this is already fixed on the master branch of `sublimehq/Packages`, see:

https://github.com/sublimehq/Packages/blob/703101afe6161d8b7b583e57a232716a5237b6e8/Markdown/Markdown.sublime-syntax#L1366

Currently, we can not simlpy update to the latest version of that subrepository (due to incompatibilities). But we could patch our Markdown.sublime-syntax locally. The file is already patched:

https://github.com/sharkdp/bat/blob/master/assets/patches/Markdown.sublime-syntax.patch

**Comment by laoshaw** [comment]
Thanks!
