### ISSUE TITLE
FR: Provide arm binaries in release

### ISSUE THREAD

**Issue by issmirnov** [sharkdp/bat#196]
Hello,

First of all, thank you for a wonderful project - this is by far my favorite colorizer. I have a small request - currently setting up a raspberry pi for some dev work, and found that there are no arm builds provided in the releases. If your release tooling is automated enough, could you add a line to build arm7?

Normally I'd compile it myself, but installing cargo on the pi and trying to build on it would be quite slow.

Thanks again!

**Comment by sharkdp** [comment]
Thank you for the feedback and your request!

Adding `arm7` as a target on Travis is not straightforward since we need to cross-compile. However, I think we should be able to use something very similar to what has been done for ripgrep (most of these changes will probably not be needed for `bat`): https://github.com/BurntSushi/ripgrep/pull/715

**Comment by sharkdp** [comment]
The new version [bat 0.5](https://github.com/sharkdp/bat/releases/tag/v0.5.0) includes pre-built binaries for ARMv7.

**Comment by issmirnov** [comment]
Thank you!! This is fantastic :)
