### ISSUE TITLE
Can't install bat w/ some other Rust apps (e.g. ripgrep) on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by InklingGirl** [sharkdp/bat#2009]
Posing this as a 'question', since every 'bug report' pertaining to this issue is quickly deemed a 'duplicate' (usually of #938) & promptly closed. To the point though, attempting to install `bat` alongside certain other Rust apps (e.g. `ripgrep`) fails, w/ the terminal outputting:

```
dpkg: error processing archive /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

So the apps' mutually shared–& to my knowledge unnecessary–file `.crates2.json` is the culprit. I understand this isn't an issue w/ `bat` or any other app itself, but rather how they've been packaged & distributed by the third-party repo contributors/maintainers. Fortunately for some of us, it's been fixed for Ubuntu 20.10 onwards…but that fix was never backported, so the issue persists for Ubuntu 20.04 LTS & has gone unsolved for years now, which is an ongoing issue for any of us who prefer to stick w/ LTS versions & find ourselves deploying multiple installs.

https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517

I am just a user, but it seems to me like it should be a trivial fix so it just installs; I don't like having to resort to hacky methods &/or extra `dpkg` steps when it should **just work**. Strongly urging any Ubuntu-using or Debian-literate developer here to intervene by going to the above link & finally fixing this. Forgive the accusatory tone, but I really do think you should take some responsibility or at least interest in how your app is represented on the latest LTS version of the world's most widely used distro, rather than dismissing it as merely not being your problem. Could someone please fix this?

Thank you.

**Comment by Enselic** [comment]
I understand your frustration. But if you want the latest Ubuntu fixes, you need to use the latest Ubuntu version. If you insist on staying on old Ubuntu versions, you have to accept that there will be bugs that have been fixed in newer versions.

In any case, there is nothing the bat project can do about this. You are barking up the wrong tree. Therefor I will close this issue now. Thank you for your understanding.

**Comment by sharkdp** [comment]
@Enselic already replied perfectly. I'm sorry, but I can't leave this sentence uncommented:

> Forgive the accusatory tone, but I really do think you should take some responsibility or at least interest in how your app is represented […], rather than dismissing it as merely not being your problem.

We *are* interested in how our app is represented in different distributions, but no: *we do not share any responsibility* (nobody does). Not for anything inside the `bat` repository (as is made pretty clear by our license files). And certainly not for bugs in packaging scripts/configs that aren't even part of our project.

And implying that we don't even *care* about this bug is just mean. I don't use Ubuntu myself. Nevertheless, I patiently reply to every Ubuntu installation problem here on this issue tracker. As you probably saw in #938, I [personally contacted](https://github.com/sharkdp/bat/issues/938#issuecomment-629164481) Ubuntu developers about the problem. I commented on the upstream issue tracker, and tried to help out [by posting a potential fix](https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517/comments/8). We provide prebuilt Debian packages for every release, offering a reasonable workaround.

> I don't like having to resort to hacky methods

The workaround suggested [here](https://github.com/sharkdp/bat/issues/938#issuecomment-646745610) is really not bad, as far as I can tell.

**Comment by InklingGirl** [comment]
@Enselic
> But if you want the latest Ubuntu fixes, you need to use the latest Ubuntu version. If you insist on staying on old Ubuntu versions, you have to accept that there will be bugs that have been fixed in newer versions.

Not quite. People use LTS releases precisely because we want more stability & reliability. That may not always pan out in practice, & indeed fixes may come slower, but 'long-term support' implies…long-term support, so it's counter to that mission for the maintainers to leave any facet of it in disrepair for so long. You're not Canonical or a part of that maintainership though, so that remark in particular isn't addressed to you but merely articulating my frustration.

@sharkdp, thank you for the response & documenting your efforts to try get this fixed, as well as for offering personalised assistance which I very much appreciate. I also apologise that what I said came off as mean. I have a couple questions then. Thank you.

> We provide prebuilt Debian packages for every release,

The pre-built .deb can't self-update &/or be kept up-to-date by the package manager though right? I'm pretty sure I would have to manually check for & install new .debs from you. Please clarify.

> The workaround suggested [here](https://github.com/sharkdp/bat/issues/938#issuecomment-646745610) is really not bad, as far as I can tell.

I've done that before & it works, but I'm trying to write a relatively clean `bash` script for post-install OS configuration that will install all my desired `apt` packages from a convenient list via 1 `sudo apt-get install` command. I'm pretty sure I can't use those switches in this [workaround](https://github.com/sharkdp/bat/issues/938#issuecomment-646745610) for anything other than `bat` (am I wrong?), & it's aesthetically a bit disheartening to have to break up my singular bulk `install` routine into a separate command on a separate line (or an `&&` sub-command) just for `bat`. Do you, or any Debian user–developers, know if what I want to do is possible?

Thank you again!

**Comment by sharkdp** [comment]
> > We provide prebuilt Debian packages for every release,
> 
> The pre-built .deb can't self-update &/or be kept up-to-date by the package manager though right? I'm pretty sure I would have to manually check for & install new .debs from you. Please clarify.

Yes, the installation would have to be updated manually. But if you are on an LTS version, you also wouldn't get the latest releases of `bat` otherwise via the official channel.

The way around this would be to create a PPA for `bat`. I have personally tried to set one up in the past (https://github.com/sharkdp/bat/issues/323#issuecomment-425533575), but gave up eventually. And nobody else felt like stepping in.

> I'm pretty sure I can't use those switches in this [workaround](https://github.com/sharkdp/bat/issues/938#issuecomment-646745610) for anything other than `bat` (am I wrong?),

I don't know. But I would imagine you could pass the required option to your single long `apt-get install` command. It's not great though, as it disables a check that is useful in principle. For a fresh install script, I think it could work though. But that's just a guess.

**Comment by InklingGirl** [comment]
> The way around this would be to create a PPA for `bat`. I have personally tried to set one up in the past ([#323 (comment)](https://github.com/sharkdp/bat/issues/323#issuecomment-425533575)), but gave up eventually. And nobody else felt like stepping in.

A PPA would quite literally seamlessly solve my problem, as my script already adds a few repos anyways that the `apt` list–which is a separate list file my script funnels into `apt-get install` via `xargs -a` (so ostensibly a 'long command', but not exactly)– later in my script draws packages from. Unfortunately, I don't currently have the skill set to set up a PPA.

> It's not great though, as it disables a check that is useful in principle.

This is of course my concern, I feel it could break something if the check is disabled for more than just `bat` & `ripgrep`. I haven't tried.

**Comment by InklingGirl** [comment]
https://bugs.launchpad.net/ubuntu/+source/rust-bat

@sharkdp it looks like the issue has a workable `fix committed`, priority `high`, but has been stuck that way w/o a merge for a fair bit now. Perhaps now is a good time to badger an Ubuntu developer / repo maintainer about this, like you had in the past? Nobody has made a `bat` PPA yet either, but the fix to the its entry in the official repos is so close to being implemented. Thank you.

**Comment by sharkdp** [comment]
There are enough comments begging for a solution in https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517 already. I don't think it will help to add even more comments along these lines.

**Comment by InklingGirl** [comment]
Most if not all of those are before the commit.

**Comment by sharkdp** [comment]
The fix is 1,5 years old...

**Comment by InklingGirl** [comment]
Ah, I can see that now. Really disappointing. Again, I hope someone will make a PPA..
