### ISSUE TITLE
`bat` prints binaries when running tests even without `--show-all`

### ISSUE THREAD

**Issue by willful759** [sharkdp/bat#2043]
I was writing some tests for my implementation of #1709 when I noticed that for whatever reason, trying print a binary file (like an image or an archive) always prints the contents of the binary file when running tests, even when testing manually works as intended.

Source code for the test:

```rust
#[test]
fn fail_if_unsupported_unsupported() {
    bat()
        .arg("--fail-if-unsupported")
        .arg("regression_tests/issue_1709.rar")
        .assert()
        .failure()
        .stdout("")
        .stderr("");
}
```

This is what happens if i run the test:

```
---- fail_if_unsupported_unsupported stdout ----
thread 'fail_if_unsupported_unsupported' panicked at 'Unexpected success
command=`"/home/willful759/dev/rust/bat/target/debug/bat" "--no-config" "--fail-if-unsupported" "regression_tests/issue_1709.rar"`
code=0
stdout="Rar!\u{1a}\x07\x01\03\x92\xB5\xE5\n\x01\x05\x06\0\x05\x01\x01\x80\x80\0\x8C\xF8\xB5\xC5&\x02\x03\x0b\x9C\0\x04\x9C\0\xA4\x83\x02\x17\'p\xBD\x80\0\x01\x08test.txt\n\x03\x13\xA6\x94\xEFaG\x0e\xED.this shouldn\'t be printable\n\u{1d}wVQ\x03\x05\x04\0"
stderr=""
', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    fail_if_unsupported_unsupported

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 83 filtered out; finished in 0.02s

error: test failed, to rerun pass '--test integration_tests'
```

Note that `bat` printed the contents of the file, instead of just saying that it is a `<BINARY>`, as you would expect if it just didn't recognize my flag.
 
Running the exact same command manually works as intended:

![image](https://user-images.githubusercontent.com/30967965/151094577-7571df17-07cd-451d-bfae-5079a18588b5.png)

Am I doing something wrong or is this actually a bug?

**Comment by Enselic** [comment]
This is caused by that the test captures stdout, which will make `atty::is(Stream::Stdout)` return `false`, which makes bat default to `cat` compatibility mode where the output is just forwarded byte-by-byte. When you run the same command in your terminal, it will return `true` instead.

You can simulate this situation locally by doing e.g. `bat --fail-if-unsupported regression_tests/issue_1709.rar | tee`. The usual way to force `bat` to keep the "terminal" output format even when output is not going to a terminal is to pass `-f`/`--force-colorization`. In your case that would be `bat -f --fail-if-unsupported regression_tests/issue_1709.rar | tee`

**Comment by willful759** [comment]
Thanks for the reply, I will look into it
