### ISSUE TITLE
Add windows build to releases?

### ISSUE THREAD

**Issue by LippyBoy** [sharkdp/bat#210]
Since bat seems to support colors in Windows 10, would it be possible to add windows binaries to the releases page with each version?

**Comment by sharkdp** [comment]
Thank you for the feedback. It is certainly possible.

I quickly tried to build `bat` in a Windows 10 VM and was surprised to see that (at least superficially) everything seems to work :sparkles: 

![image](https://user-images.githubusercontent.com/4209276/44422966-0650eb80-a585-11e8-8793-fe0933bcbc56.png)

I'm a little hesitant because maintaining a working Windows version has lead to a huge amount of work in two other Rust projects of mine [[1]](https://github.com/sharkdp/fd) [[2]](https://github.com/sharkdp/hyperfine).

I'm inclined to say "yes" though, if:
- Someone takes over the work to create an `appveyor.yml` configuration such that we have CI for Windows (Note: the `git2` crate requires CMake, so that needs to be installed in the AppVeyor images). This would also involve some work on getting the unit tests up and running (some of them do fail on Windows).
- We don't have to add huge amounts of `#[cfg(windows)]` parts throughout the code base.
- We only try to support Windows 10 + PowerShell. `cmd.exe` is a pain

**Comment by be5invis** [comment]
> We only try to support Windows 10 + PowerShell. cmd.exe is a pain

I do not think PowerShell is a key part since `bat` is an EXE rather a shell script.
Some notes: box-drawing glyphs under Chinese or Japanese OSes may occupy two console cells rather than one, so be careful.

**Comment by sharkdp** [comment]
> I do not think PowerShell is a key part since bat is an EXE rather a shell script.

I'm certainly not an expert but there are things where we could (or would) run into potential problems:

- ANSI colors do not work in `cmd.exe` and I don't want to switch to a another terminal-color library.
- Argument parsing in `cmd.exe` is weird (https://github.com/sharkdp/fd/issues/299).

**Comment by keith-hall** [comment]
For reference, I can confirm that `bat` is correctly showing syntax highlighting in Windows 7 using PowerShell 6 inside [ConEmu](https://conemu.github.io/), although I had to execute with `--color=always`.

**Comment by mattpodwysocki** [comment]
@sharkdp I appreciate the work done here on bat and I do use it on my Windows machine as part of my work at Microsoft. I'd agree that targeting PowerShell or PowerShell-Core is the right thing to do since cmd.exe is no longer being actively developed according to @bitcrazed.  I'd love to have it prepackaged so that I can get it straight from here or a package manager such as Chocolatey or Scoop!

**Comment by be5invis** [comment]
@sharkdp Any console app can call `SetConsoleMode` with `ENABLE_VIRTUAL_TERMINAL_PROCESSING` to enable ANSI support in CMD, or "directly double-click the EXE".
PowerShell called it when starting so processes inherited its ability.

**Comment by be5invis** [comment]
Hmmm, looks like `ansi_term` already had it: https://github.com/ogham/rust-ansi-term/blob/master/src/windows.rs

**Comment by sharkdp** [comment]
We managed to get all unit tests running on Windows (see #231) and @anykao set up an AppVeyor configuration such that we will have pre-built binaries for Windows starting with v0.6.1 which I have just released:

https://github.com/sharkdp/bat/releases/tag/v0.6.1

Colors work in PowerShell as well as cmd.exe (only tested on Windows 10)

![image](https://user-images.githubusercontent.com/4209276/44938901-c4445880-ad81-11e8-94af-e72fa1225103.png)
