### ISSUE TITLE
Inconsistent reaction between -L and --help 

### ISSUE THREAD

**Issue by meeas** [sharkdp/bat#2150]
**Describe the bug you encountered:**

When you run `bat -L` the response is to show the list of languages inside the pager.  However when you run `bat --help` the response is to dump multiple pages to STDOUT without a pager.  

**What did you expect to happen instead?**

I expected both to use the pager

**How did you install `bat`?**

Debian Sid repository

---

Bat v0.20.0
Fish v3.4.1

Same happens on Bash v5.1.16(1)

bat has been built without the 'bugreport' feature. The '--diagnostic' option is not available.

**Comment by keith-hall** [comment]
Thanks for reporting. We are tracking this under https://github.com/sharkdp/bat/issues/1587

**Comment by sharkdp** [comment]
> **How did you install `bat`?**
> 
> Debian Sid repository


> bat has been built without the 'bugreport' feature. The '--diagnostic' option is not available.

Oh wow, really? You installed from official Debian sources and it's built without the `bugreport` feature?

**Comment by Enselic** [comment]
Maybe I was overly generous when I made `bugreport` optional? More than once have I built `minimal-application` and then being annoyed that I couldn't get `--diagnostics`. The reason I made it optional was because `bugreport` has a dependency on the `git-version` crate, and I figured it would be good to support building entirely without git. However, `git-version` is optional in `bugreport`, so we could make `bugreport` mandatory, but `bugreport` with `git-version` optional.
