### ISSUE TITLE
Different color scheme in Alacritty

### ISSUE THREAD

**Issue by dikiaap** [sharkdp/bat#220]
The color scheme works well in LXTerminal, but in Alacritty where the color scheme becomes slightly reduced.

![ss](https://user-images.githubusercontent.com/8542502/44616943-37326880-a884-11e8-9e6c-d54cb8114a0d.png)

Default:

![ss2](https://user-images.githubusercontent.com/8542502/44616944-37caff00-a884-11e8-90db-c002bb505481.png)

In the default theme, the orange and magenta color is also reduced.

**Comment by sharkdp** [comment]
Thank you for the feedback.

I can not reproduce this. I am using `alacritty 0.1.0` with [this configuration](https://gist.github.com/sharkdp/846a8d49e9ad77db2899435a2842bb9a).

Can you please post your alacritty config and check whether `$COLORTERM` is set to `truecolor`?

**Comment by sharkdp** [comment]
Actually, it seems that `alacritty` does not set the `$COLORTERM` variable. I accidentally started `alacritty` from `terminator`, which is why I had `$COLORTERM` set.

Could you try to `export COLORTERM=truecolor` and see if that fixes the colors? Still, something seems weird with your `alacritty` configuration. There shouldn't be any background colors. Even in 8bit mode (no truecolor support) with interpolated colors, it looks fine for me (although differences are noticeable).

**Comment by dikiaap** [comment]
@sharkdp Yes, It's not set in here. I just tried exporting that and it works now. Thank you!

**Comment by sharkdp** [comment]
I'm going to reopen this because there should probably be another way to detect truecolor support for a given terminal.

If not, we should at least document the behavior concerning the `COLORTERM` environment variable.

For reference: https://gist.github.com/XVilka/8346728

**Comment by sharkdp** [comment]
I have added a "Troubleshooting" section to `bat`s README and I have opened [a ticket](https://github.com/jwilm/alacritty/issues/1526) for alacritty to discuss the support for the `COLORTERM` variable ([corresponding PR](https://github.com/jwilm/alacritty/pull/1527)).

**Comment by sharkdp** [comment]
The upstream ticket has been solved.

Until the fix has been released, you can also set `COLORTERM` in your `alacritty.yml`:

``` yml
env:
  # ...
  COLORTERM: truecolor
```

which is probably better than exporting it in your shells init file, because that would affect other terminals as well.
