### ISSUE TITLE
Snap package for Ubuntu

### ISSUE THREAD

**Issue by KindDragon** [sharkdp/bat#241]
Please create Snap package and maintain
https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0

**Comment by cimm** [comment]
I discovered `bat` through the [CLI: improved](https://remysharp.com/2018/08/23/cli-improved) article featured on HackerNews, what a great tool!

The Linux package does currently not autoupdate (since you need to download / install it manually), a [snap](https://snapcraft.io/) package could solve this. Have a look at the snap [forum](https://forum.snapcraft.io/categories) if you need some help.

**Comment by sharkdp** [comment]
I am personally not going to create and maintain a Snap package.

If anyone wants to work on this, I'm happy to support the effort, though.

**Comment by initbar** [comment]
@sharkdp I would like to take a shot at this and maintain future releases on `snap`. Can I be assigned?

**Comment by sharkdp** [comment]
@initbar Absolutely! Any help is greatly appreciated.

> Can I be assigned?

I'm not allowed to do that :smile: Can you add yourself?

**Comment by sharkdp** [comment]
I'm going to close this, as the development probably won't happen in the `bat` repository. If someone decides to create a Snap package for `bat`, please inform me and we will add a section in the README.
