### ISSUE TITLE
Color theme should take background color into account

### ISSUE THREAD

**Issue by Lapizistik** [sharkdp/bat#261]
I use different terminals, some with black font on light background, others with white font on black background. It is very hard to read the output of several themes on terminals with light background colour. It would be helpful if bat could autodetect this and invert colors (or give the printed lines a background color.

**Comment by sharkdp** [comment]
I don't think there is a reliable way to detect the terminals background color (https://stackoverflow.com/questions/2507337/is-there-a-way-to-determine-a-terminals-background-color), so this is probably not going to happen.

**Comment by sharkdp** [comment]
I have tried that, but it looks terrible because the background color changes in the middle of your terminal session. I wouldn't want any CLI program to do that. You also need to do things like filling short lines with spaces just to "draw" the background color.

**Comment by morenoh149** [comment]
can you add a light/dark flag to control the theme? I use solarized light and white text is unusable on it

**Comment by vimpostor** [comment]
> I don't think there is a reliable way to detect the terminals background color, so this is probably not going to happen.

While that is technically true - there is no 100% reliable way to detect that - there exists many possible workarounds to find out whether the terminal is in dark mode or in light mode. For example, vim has been checking `$COLORFGBG` successfully for years to detect the terminal background: https://github.com/vim/vim/blob/748b308eebe8d8860888eb27da08333f175d547d/src/term.c#L3038

I think bat should add such workarounds too, because bat's default is literally unusable on a light terminal theme right now.

Would you accept a PR implementing one of those ways to check for the terminal background?

**Comment by Enselic** [comment]
If `COLORFGBG` is set and indicates a white/light background, I think it makes a lot of sense for bat to default to `Monokai Extended Light`. If `COLORFGBG` is not set, the default should remain the same.

It will not work in all situations, but it will work in some, and working sometimes is better than never working. Once the infrastructure is in place, others can add more checks for more environments, if the checks are sufficiently cheap and reliable.

This is just my personal opinion. Not sure if other maintainers agree.

**Comment by vimpostor** [comment]
What do you think about just using https://github.com/dalance/termbg and having it do the work for us. It's a library that supports detecting the background with OSC queries reliably and it uses `$COLORFGBG` as fallback.

**Comment by Enselic** [comment]
My main concern with doing OSC queries at startup is how much it affects startup time. Maybe it's plenty fast. It would be good if someone could throw together a prototype where that can be explored.
