### ISSUE TITLE
Unicode rending issue

### ISSUE THREAD

**Issue by Kyle-Ye** [sharkdp/bat#2700]
**What steps will reproduce the bug?**

1. copy the following unicode into test.txt 
```
🤦🏼‍♂️
```
2. bat test.txt

**What happens?**

<img width="357" alt="image" src="https://github.com/sharkdp/bat/assets/43724855/0ccda3dc-281a-417e-ae5b-3455070aaa1c">

> cat will give the same result. But I did not expect cat to fully support the latest unicode.

**What did you expect to happen instead?**

```
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ./test.txt
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 🤦🏼‍♂️
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────
```

**How did you install `bat`?**

HomeBrew

**bat version and environment**

bat 0.23.0

**Other Information**

The issue maybe related to the unicode crate this project is currently using.

![image](https://github.com/sharkdp/bat/assets/43724855/f31c9733-0380-4526-a692-de561f77b170)

https://hsivonen.fi/string-length/
https://tonsky.me/blog/unicode/

**Comment by einfachIrgendwer0815** [comment]
When running:
```bash
bat test.txt | bat --show-all --plain
```
I get:
```
\u{1f926}\u{1f3fc}\u{200d}\u{2642}\u{fe0f}␊
```
According to https://hsivonen.fi/string-length/, that seems to be the correct representation of the 🤦🏼‍♂️ character:
![](https://github.com/sharkdp/bat/assets/85333734/1473b56f-de02-49e6-ae6e-c9655a4ab10f)

When I write the output of `bat test.txt` into a file:
```bash
bat test.txt > output.txt
```
and open that file in gedit or vs code, I get the following correct looking results:
![](https://github.com/sharkdp/bat/assets/85333734/19225486-4586-41b2-b5d4-344e611960dd)
![](https://github.com/sharkdp/bat/assets/85333734/67b7b320-ba31-4174-bffd-a0bee47d41b7)

So, I think that this issue is not caused by bat but the terminal rendering the 🤦🏼‍♂️ character incorrectly.

**Comment by keith-hall** [comment]
One think to check is `bat` with `--paging=never` to rule out the pager (i.e. `less`) somehow changing the output
