### ISSUE TITLE
Wrap=never and bat config not working on macOS

### ISSUE THREAD

**Issue by ciscohack** [sharkdp/bat#2754]
Hello Expert,

I just migrated to a new Mac device running macOS 14. I have installed the BAT tool through homebrew. Now when I run the bat config command to read the config I get an error and also bat --wrap=never seems broken and even with this option turned on line is wrapped up or truncated.

I tried reinstalling but no luck. need your help to fix the issue

#### Software version

bat 0.24.0

#### Operating system

macOS 14.0 (Darwin 23.0.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=-iRFXMx4
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=gruvbox-dark
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=moar
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

Could not read contents of '/Users/praverai/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

```
bat_version: 0.24.0
creation_time:
  secs_since_epoch: 1697177103
  nanos_since_epoch: 150970000
```

#### Custom assets

- metadata.yaml, 97 bytes
- syntaxes.bin, 915557 bytes
- themes.bin, 45833 bytes

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
- Host: aarch64-apple-darwin

#### Less version

```
> less --version
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by ciscohack** [comment]
@sharkdp Any help on this issue? please!

**Comment by eth-p** [comment]
Just to clarify, when you mean the line is wrapped, do you mean like the screenshot on the left, or the screenshot on the right?

<table><tr><td>
<img width="527" alt="image" src="https://github.com/sharkdp/bat/assets/32112321/e3c42d54-04c0-4b15-8191-bb66faeeae6e">
</td>
<td>
<img width="533" alt="image" src="https://github.com/sharkdp/bat/assets/32112321/3abcfcaf-6d8e-4498-a6f9-86709ff1cc97">
</td></tr></table>

The wrapping on the left is caused by `bat`, while the wrapping on the right is caused by `less`. You can remove the wrapping introduced by `less` by using `bat`'s `-S`/`--chop-long-lines` option or adding the `-S` option to your `LESS` environment variable:

<img width="529" alt="image" src="https://github.com/sharkdp/bat/assets/32112321/f2381e5f-6cb7-4821-aa19-6b2ca33a24aa">
