### ISSUE TITLE
bat aliased as cat

### ISSUE THREAD

**Issue by niksingh710** [sharkdp/bat#2801]
i am using `alias cat="bat -p"`

now sometime i want it to be in paged mode for that moment i have `alias catt="bat"` i want a flag like `--pager-forced` that can set the current view in paged mode so that i can use that with `cat` alias.

**Comment by eth-p** [comment]
If you don't mind using a function instead of an alias, this should be able to achieve what you want:

```bash
catt() {
    local paged=false
    local batarg=()
    local arg
    for arg in "$@"; do
        case "$arg" in
            --paged) paged=true ;;
            *) batarg+=("$arg") ;;
        esac
    done

    if ! "$paged"; then
        batarg+=(-pp)
    fi

    bat "${batarg[@]}"
    return $?
}
```

If you use `catt file.txt`, it won't use decorations or the pager. If you use `catt file.txt --paged`, it will use the default behavior with the options you set in the config file or through the `BAT_*` variables.

**Comment by niksingh710** [comment]
@eth-p thanks mate this seems to be a nice solution, I have tried it earlier but my management of args wasn't like this.
Thanks for giving this fn snippet.

**Comment by eth-p** [comment]
@niksingh710 Happy to help!
