### ISSUE TITLE
bat shows BOM at the start of the line

### ISSUE THREAD

**Issue by rasjani** [sharkdp/bat#285]
when the source code has BOM at the begining of the line, its shown as "<U+FEFF>". I have now huge problem with this per se but it would be more user friendly to strip that piece away when showing the code and putting that info as interpreted value into same line as "File:" is, like additional piece  "Encoding: UTF-16 Big Endian" .. 

Happens atleast with bat 0.5.0

See https://en.wikipedia.org/wiki/Byte_order_mark for details

**Comment by rasjani** [comment]
Yeah, this came up in  a c# code that only targets windows.  But to be honest, i didnt check if that FEFF bom was BE or LE :)

**Comment by lzybkr** [comment]
There was a commonly used Windows tool that generated UTF-16BE files by default (for no good reason really), but the default was thankfully changed to UTF8.

When adding BOM detection, it would be great to convert UTF16 to UTF8. Right now, UTF16-LE renders `^@` between each character, presumably because the text is being treated as UTF8, e.g.:

![image](https://user-images.githubusercontent.com/2148248/46566193-c17fda80-c8ce-11e8-8a5f-83a94b8187b8.png)

**Comment by lzybkr** [comment]
> Notepad? :-)

That'd be funny, but no, it was `powershell_ise.exe`.

Thanks for the quick fix.

**Comment by sharkdp** [comment]
Released in [v0.8.0](https://github.com/sharkdp/bat/releases/tag/v0.8.0). @rasjani Could you please check if this works for you?
