### ISSUE TITLE
iTerm2 issue with fullscreen

### ISSUE THREAD

**Issue by scalp42** [sharkdp/bat#294]
Thanks a lot for `bat`!

I just noticed that if you `bat` a file in iTerm2 and simply keep switching back and forth to fullscreen, the output gets messed up pretty bad.

Here is an example, `bat` a file belonging to Homebrew:

<img width="1440" alt="screen shot 2018-09-07 at 8 26 42 pm" src="https://user-images.githubusercontent.com/1475276/45249848-69a88080-b2dc-11e8-90a4-98733b1d4403.png">

<img width="1440" alt="screen shot 2018-09-07 at 8 26 45 pm" src="https://user-images.githubusercontent.com/1475276/45249849-6ca37100-b2dc-11e8-9e15-d866fcc5fa21.png">

Now if I simply get out of fullscreen, output gets messed up:

<img width="697" alt="screen shot 2018-09-07 at 8 27 51 pm" src="https://user-images.githubusercontent.com/1475276/45249859-81800480-b2dc-11e8-95d0-03e1cdca8669.png">

<img width="1440" alt="screen shot 2018-09-07 at 8 28 39 pm" src="https://user-images.githubusercontent.com/1475276/45249872-a70d0e00-b2dc-11e8-89eb-77dd65601c91.png">

You can also see the scrollbar in the terminal growing, simply switching back and forth to fullscreen (cmd+enter):

<img width="697" alt="screen shot 2018-09-07 at 8 29 42 pm" src="https://user-images.githubusercontent.com/1475276/45249883-d1f76200-b2dc-11e8-824d-418c58f81d83.png">

Not even sure where to start with this, but let me know if I can help!

**Comment by eth-p** [comment]
> You can also see the scrollbar in the terminal growing

This is because of `less`, not `bat`. `less` will automatically resize itself with the terminal, which involves re-printing everything. The content that was on the screen before the re-print is pushed back into the scrollback buffer, which creates a jumbled mess when scrolling back up.

If you disable the pager with `--paging=never`, this shouldn't happen anymore. A more permanent fix would be to add `export BAT_PAGER=cat` to your `.bashrc` file, though.

---

As for the last image: the line wrapping fails because the terminal was resized to a smaller width than when it was printed, which makes iTerm's text wrapping take over. Unfortunately, once `bat` passes control to the pager, there's no way redraw/refresh the output to fit the smaller terminal.

**Comment by sharkdp** [comment]
Thank you for helping out here, @eth-p. Just a minor comment: To disable the pager permanently, you can use `export BAT_PAGER=""` (instead of setting it to `cat`). This way, `bat` will not spawn an additional process.

**Comment by scalp42** [comment]
`export BAT_PAGER=""` working great!

Thanks for the help, closing ❤️
