### ISSUE TITLE
no license text for bundled Nord-sublime theme

### ISSUE THREAD

**Issue by decathorpe** [sharkdp/bat#2987]
The "Nord-sublime" theme bundled [here](https://github.com/sharkdp/bat/tree/v0.24.0/assets/themes) keeps the license header from the original project before the fork (`License:    MIT`), but it doesn't contain a copy of the MIT license text. However, the MIT license *requires* that redistributed sources contain a copy of the license text.

I would suggest to file an issue with the [upstream project](https://github.com/crabique/Nord-plist) about explicitly adding the license text as a file. If that doesn't happen, I don't think bat can redistribute this theme.

**Comment by einfachIrgendwer0815** [comment]
> If that doesn't happen, I don't think bat can redistribute this theme.

I agree that upstream probably has a licensing issue. However, the code they forked is still MIT-licensed anyway. They kept the license header, so their changes are also under the MIT license. Since it's all MIT-licensed, I think the bat project should be able to distribute the theme as long as it provides the license text.  I am definitely not a lawyer though...
