### ISSUE TITLE
FEAT: add support for hyprlang

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [sharkdp/bat#3122]
The [Hyprland](https://github.com/hyprwm/Hyprland) compositor uses a unique configuration language called [hyprlang](https://github.com/hyprwm/hyprlang). I was wondering if we could add support for this as well. As it uses `.conf` extension, I think that you will have to look at `~/.conf/hypr/*.conf` for example. Or there might be something that you know more than me about this.

**Comment by keith-hall** [comment]
I can't see any syntax definition on packagecontrol.io for this. I wonder if some existing syntax is good enough? Ruby or Terraform might get you some of the way there.

```sh
TEXT=$(cat <<EOF
bakery {
    counter_color = rgba(ee22eeff)          # color by rgba()
    door_color = rgba(122, 176, 91, 0.1)    # color by rgba()
    dimensions = 10 20                      # vec2
    employees = 3                           # int
    average_time_spent = 8.13               # float
    hackers_password = 0xDEADBEEF           # int, as hex

    # nested categories
    secrets {
        password = hyprland                 # string
    }
}

# variable
 = 3

cakes {
    number =                     # use a variable
    colors = red, green, blue               # string
}

# keywords, invoke your own handler with the parameters
add_baker = Jeremy, 26, Warsaw
add_baker = Andrew, 21, Berlin
add_baker = Koichi, 18, Morioh
EOF
)

echo "$TEXT" | bat -l Ruby
echo "$TEXT" | bat -l Terraform
```

**Comment by ZeyadMoustafaKamal** [comment]
I don't understand is it mandatory to have a package for syntax definition on packagecontrol.io ? I thought it's like keyword matching and this ? if it's mandatory then forget about it but if not please tell me exactly what you need and I might contact with the developer and ask him for what you need.

**Comment by keith-hall** [comment]
If you want `bat` to ship with specific support for highlighting an additional language out of the box, then we have a requirement or guideline that the syntax package should have ovor 10,000 downloads on packagecontrol.io, so that `bat` doesn't get bloated with things the average user won't use.

If you want to make your own `sublime-syntax` for a language (which is a bit more powerful than "just" keyword matching), then of course you are free to do so and use it without submitting it to package control.

**Comment by ZeyadMoustafaKamal** [comment]
I have never done such a thing but it seems to be the way to go. But I want to know, will the `.sublime-syntax` auto detect the language or when I add a new language I have to specify it as an argument to the cli ?

**Comment by keith-hall** [comment]
The `sublime-syntax` itself supports mapping by filename/extension only. As `.conf` is very generic, you'd instead want to configure a syntax mapping on the path `~/.conf/hypr/*.conf`, which can be done in a configuration file so that it doesn't have to be specified on the command line each time - see https://github.com/sharkdp/bat?tab=readme-ov-file#adding-or-changing-file-type-associations.

**Comment by ZeyadMoustafaKamal** [comment]
Ok. thanks a lot.

**Comment by WhySoBad** [comment]
Hi,
I just found that there is a hyprlang sublime grammar available here: https://github.com/0x000C0A71/hyprlang-sublime-syntax

Would it be possible to reopen this issue and add hyprlang support to bat? :)
