### ISSUE TITLE
Slow display with the -p flag

### ISSUE THREAD

**Issue by nloadholtes** [sharkdp/bat#348]
Using the -p flag slows bat down considerably.

If I do bat -p some-minified-file.js it is incredibly slow to show each screenful, as in it takes over 2 seconds to draw the first page on the screen. Each page displays slower than the one before it, on the 3rd page I counted to 14 before it stopped rendering.

But if I do bat some-minified-file.js it is much faster, especially as I view each page. There doesn't seem to be any slow down as I page through the file.

Background: The js file is 381975 bytes. I noticed this because I made an alias for more to be bat -p.

**Comment by sharkdp** [comment]
Thank you for reporting this.

I can reproduce this, but I don't think this is a problem with `bat`, but rather with `less`.

If I benchmark `bat` with "full" decorations and with "plain" / no decorations, there is hardly any difference (`-p` is slightly faster, as expected):

``` bash
BAT_PAGER="" hyperfine \
  --show-output \
  "bat jquery.min.js" \
  "bat jquery.min.js -p" \
  --export-markdown bench.md
```

| Command | Mean [ms] | Min…Max [ms] |
|:---|---:|---:|
| `bat jquery.min.js` | 814.8 ± 16.1 | 805.5…859.5 |
| `bat jquery.min.js -p` | 793.6 ± 29.7 | 762.5…849.6 |

However, when we run both commands with the pager enabled, there is a huge performance difference. The "plain" mode (`-p`) output renders much slower within `less`. I think this might be due to character-level wrapping being disabled in `bat`s "plain" mode. This causes `bat` to print out one really long line (instead of several lines that *just* fill the screen). This can be verified by using "plain" mode with wrapping enabled.

For me, this is fast:
```
bat jquery.min.js -p --wrap=character
```

While this is very slow:
```
bat jquery.min.js -p
```

**Comment by nloadholtes** [comment]
I think you are correct about `less` being the source of the issue, I re-ran my test with the Activity Monitor running. The system was almost idle when I re-ran the test and I saw a spike of CPU activity:

![image](https://user-images.githubusercontent.com/344995/46767453-0a5ed700-ccb3-11e8-8a8b-3306c2abc4ed.png)

**Comment by sharkdp** [comment]
Another option is to use the `-S`/`--chop-long-lines` option of `less`.

https://superuser.com/questions/272818/how-to-turn-off-word-wrap-in-less

To use this with bat, see https://github.com/sharkdp/bat#using-a-different-pager
