### ISSUE TITLE
could you add edit mode?

### ISSUE THREAD

**Issue by FoxDaxian** [sharkdp/bat#358]
bat is awesome plugin, even if like now, bug it's a pity that you can't edit.

**Comment by FoxDaxian** [comment]
just like sample vim...

**Comment by sharkdp** [comment]
This is definitely out of the scope for this project (see [Project goals](https://github.com/sharkdp/bat#project-goals-and-alternatives)).

I quickly thought about the possibility to open an external editor from the pager (`less`). There is actually a key for this (`v` - *Invokes  an  editor  to edit the current file being viewed*), but this doesn't work since we pass input to `less` via standard input. It therefore just shows "Cannot edit standard input". There is the `LESSEDIT` command-line option that allows users to change the way the editor is invoked, but apparently it's not possible to bypass the "Cannot edit standard input" error.

**Comment by FoxDaxian** [comment]
wow, do you have a plan to make a vim version? : D

**Comment by sharkdp** [comment]
I don't really know what you mean by "vim version", but I think this discussion is leading nowhere. I'm going to close this, but feel free to comment here if you think there is still valuable feedback.

**Comment by chaoyi** [comment]
> This is definitely out of the scope for this project (see [Project goals](https://github.com/sharkdp/bat#project-goals-and-alternatives)).
> 
> I quickly thought about the possibility to open an external editor from the pager (`less`). There is actually a key for this (`v` - _Invokes an editor to edit the current file being viewed_), but this doesn't work since we pass input to `less` via standard input. It therefore just shows "Cannot edit standard input". There is the `LESSEDIT` command-line option that allows users to change the way the editor is invoked, but apparently it's not possible to bypass the _"Cannot edit standard input"_ error.

Bash process substitution could be used to bypass the _"Cannot edit standard input"_ error.  Something similar to
`function open-in-emacs { LESSEDIT="emacsclient -nw ?lm+%lm. \"$1\"" LESS= less -fR <(bat --color=always "$1"); }`
