### ISSUE TITLE
Jump to line with +

### ISSUE THREAD

**Issue by Jab2870** [sharkdp/bat#397]
When starting vim, you can easily jump to a new line by typing

```bash
$ vim my-file.txt +30
```
This would position the cursor on line 30.  It would be very helpful to have similar functionality from bat

**Comment by sharkdp** [comment]
THank you for the feedback.


Have you see #388?

**Comment by Jab2870** [comment]
Thank you, I didn't see that when I searched, thanks.

The `--pager="less +300G"` option is what I will use although it is a lot of typing.

**Comment by cohml** [comment]
> The `--pager="less +300G"` option [...] is a lot of typing.

I agree. Not only that, but if you have `--pager` set to something else (which in my case is quite complex), it's a bummer that jumping to a line would necessitate overriding that value.

I saw on #388 that this is a job for the paper, not `bat`, and I understand why (because we're really talking about paging here, which `bat` doesn't do), but I wish it could 😿
