### ISSUE TITLE
Wrong parameter parsing.

### ISSUE THREAD

**Issue by goldragoon** [sharkdp/bat#44]
Obiviously, as depicted below, bat command recognizes filename (R-language source code) as subcommand.

If this error doesn't come from my misuse, i'll fix it. 

<img width="912" alt="2018-05-03 9 43 18" src="https://user-images.githubusercontent.com/2537598/39555820-f6974024-4eb6-11e8-8a4f-4d5bb21a0e7b.png">

**Comment by sharkdp** [comment]
Oh, I guess I shouldn't have mixed positional arguments and sub-commands. That was a bad idea. Thank you for reporting this.

The problem seems to be with the `help` subcommand that `clap` enables as soon as we have at least one subcommand (`init-cache`). `clap` seems to think that you wanted to call `bat help` due to the name of the file (triggered by any file named `hel...`). Similar problems occur with files named (`ini...`). We should get rid of the subcommands and turn `init-cache` into a command-line option.
