### ISSUE TITLE
Add Nim lang in default syntax 

### ISSUE THREAD

**Issue by raivivek** [sharkdp/bat#542]
Hi, I think adding [Nim](https://nim-lang.org) will be an useful addition. Example of a Sublime Text extension that provides syntax highlighting support is available here: https://github.com/Varriount/NimLime

Other resource if first is not sufficient: https://github.com/nim-lang/Nim/wiki/Editor-Support

**Comment by sharkdp** [comment]
Sounds good!

**Comment by sharkdp** [comment]
Unfortunately, I wasn't able to generate a `.sublime-syntax` file from the NimLine `.tmLanguage` syntax.

**Comment by sharkdp** [comment]
Closing this, as I see no way on how to proceed here. I'm not going to manually convert the `tmLanguage` file.

**Comment by Nindaleth** [comment]
Not sure if anyone can still read this as the issue is closed...

But there's at least an option of `.sublime-syntax` workaround: https://github.com/Varriount/NimLime/issues/90#issuecomment-451684755
It's from October 2017 and kinda unmaintained, but between potentially incomplete syntax highlighting and _nonexistent_ syntax highlighting for Nim, you might prefer something over nothing.

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).
