### ISSUE TITLE
this simple program needs 143 library . why ?

### ISSUE THREAD

**Issue by catastrop** [sharkdp/bat#589]
This is like nodejs like people

**Comment by jfrimmel** [comment]
First of all, this is not a "simple program", there are several thousand lines of code.
Secondly, this program only depends on __14__ crates (as the libraries are called). All other crates are indirect dependencies, pulled in by those 14 crates.
Third, I don't see any problems having a well-choosen list of dependencies __if__ there is a good dependecy management, which there is in Rust. What are the downside of having many small, self-contained crates instead of one or two monoliths? The compile-time will most likely be faster, especially using incremental compilation.
