### ISSUE TITLE
Feature Request: nix-shell shebang support

### ISSUE THREAD

**Issue by CarlOlson** [sharkdp/bat#684]
`nix-shell` has the interpreter on the second line, examples:
https://gist.github.com/travisbhartwell/f972aab227306edfcfea

**Comment by sharkdp** [comment]
Thank you for your request.

We will probably not be able to support this, since `bat` works in streaming mode. It has to decide on a syntax when reading the first line (or before printing the first line).

The reason is that we have to support things like this:
```
some-program-that-outputs-nix-shell-code | bat
```
At the same time, we need to show the first line of output after we receive the first line of input (non-buffered mode) for interactive use.
