### ISSUE TITLE
Add option to display all supported languages

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#69]
Maybe:
```
> bat --list-languages
ActionScript			as
AppleScript				applescript
ASP						asa
Batch File				bat, cmd
C#						cs, csx
...
```

See: https://docs.rs/syntect/2.0.1/syntect/parsing/struct.SyntaxSet.html#method.syntaxes

**Comment by connorkuehl** [comment]
I'd like to work on this. I played around with it a little bit and I have the basic functionality working as described above.

```
./target/debug/bat.exe --help
bat 0.2.3
A cat(1) clone with wings.

USAGE:
    bat.exe [OPTIONS] [FILE]... [SUBCOMMAND]

OPTIONS:
---snipped---

        --list-languages
            Displays supported languages

--snipped--

```

Like this:
```
Batch File                      bat, cmd
NAnt Build File                 build
C#                      cs, csx
C++                     cpp, cc, cp, cxx, c++, C, h, hh, hpp, hxx, h++, inl, ipp
C                       c, h
CSS                     css, css.erb, css.liquid
Clojure                 clj
D                       d, di
Diff                    diff, patch
```

I'll need to work up something a bit more flexible if we want all the columns to line up correctly.

**Comment by sharkdp** [comment]
Cool, thank you very much! Getting the longest syntax name first should be fine. It's not like this has to be performance-optimized in any sense.

**Comment by sharkdp** [comment]
(also: `bat` works on Windows just like that? nice! :smile:)

**Comment by connorkuehl** [comment]
Sounds good! I’ll check back in here if I have issues or with a PR once I’m
done.

I think the issues I had getting `bat` to work were not `bat`s fault so
far.

When building, you have to build from a x64 Developer Command Prompt (which
is installed with Visual a studio/build tools) because `onig_sys` (which
must be a dependency of one of `bat`s deps) ships a custom windows bat
build script that uses tools that aren’t in the normal PATH.

`bat`s config seems to use both `%APPDATA%\Roaming` and `%APPDATA%\Local`
to draw on config files. Which is weird. Maybe one for themes and the other
for syntax packages. I don’t exactly recall. I just created symlinks in
both of those locations pointing to where I set up my `bat` config
directories.
