### ISSUE TITLE
bat --list-themes fails with SIGSEGV

### ISSUE THREAD

**Issue by jswny** [sharkdp/bat#701]
<img width="658" alt="Screen Shot 2019-10-24 at 2 02 31 PM" src="https://user-images.githubusercontent.com/3282078/67512519-fb9d5500-f666-11e9-87f7-575a8e26a735.png">

As you can see, when I run `bat --list-themes`, the command fails with `SIGSEV`. I tried this in Bash and Fish, both resulted in the same failure.

I'm running this on MacOS Catalina `10.15`, and I have `bat` version `0.12.1` installed via Brew.

**Comment by eth-p** [comment]
The `--list-themes` flag highlights the theme previews with Syntect. The segfault you encountered is likely related to #680, which is caused by an incompatibility with oniguruma (the regex library used by Syntect) and macOS 10.15.

This should be fixed in the next release.

**Comment by jswny** [comment]
@eth-p Thanks, I've been taking a look at that issue and the related ones. Is there any way to work around this problem and build `bat` manually? I couldn't seem to find a definitive workaround in the linked issue.

**Comment by eth-p** [comment]
There isn't any workaround, unfortunately. If you don't mind getting your hands dirty and building bat yourself, there is a fix in #680 though. It involves building `onig` with the latest oniguruma master and using that instead of the version syntect specified.

I'm not entirely sure on the process, but I assume you would need to clone syntect and change its `Cargo.toml` to reference the latest `onig` crate (which fixed the segfaults), and then change bat's `Cargo.toml` to reference your local copy of syntect.

**Comment by jswny** [comment]
@eth-p Ok thank you, I will try to do it manually for now.

**Comment by sharkdp** [comment]
@jswny Thank you for reporting this. I think we close this as a duplicate of #680?

**Comment by jswny** [comment]
@sharkdp Yes I think so, sorry for not finding that issue earlier, I was having a hard time figuring out what actually was going wrong to search for similar issues.

**Comment by sharkdp** [comment]
no worries, thanks.
