### ISSUE TITLE
Library API: Input Source

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#729]
I've been thinking of ideas for the library API that can provide more powerful functionality, while also reducing how much of the bat internals are exposed. Feedback would be appreciated.

---

I think we should rework/refactor input sourcing for `bat`-as-a-library. The current implementation only allows specifying input sources (via `InputFile`) from STDIN, the filesystem, and the embedded preview string.

For an API, we should have something a bit more generalized:

- Accepts any `Read` trait as an input source.
- Accepts any string as an input source.
- Contains custom "properties" (see below)
- Contains metadata (e.g. syntax name, file name, file encoding, etc.)

## Properties:

For extensibility, there should be some way to add extra fields ("properties") to an input source. This would allow features to be implemented cleanly without significantly modifying the internal code. One example would be moving the git change data into a property, and passing the property to the `Decoration` impl instead of the `InteractivePrinter`.

There are a couple ways we could implement this:

**Generics:**

We could make everything generic, and put all the properties in a single struct.
This would be fairly performant since all the hard work is done at compile-time, but it wouldn't work well when mixing external code (e.g. custom decorations) with built-in features.

**HashMap<&'static str, Any>:**

Rather than having to know everything at compile-time, we could use a hashmap of `Any`. This would allow us to split off parts of `bat` into cargo features (e.g. git support), and allows for mixing and matching of various types of properties.

Both the `HashMap` and `Any` will incur a runtime performance hit, but that could easily be mitigated by using a builder that reads and caches the data once per input source:

```rust
trait SomethingBuilder {
    fn create(&mut self, input: &Input) -> Box<dyn Something>;
}

struct MySomethingBuilder {}
impl SomethingBuilder for MySomethingBuilder {
    fn create(&mut self, input: &Input) -> Box<dyn Something> {
        Something::new(
            input.properties()
                .get("thing")
                .and_then(|v| v.downcast_ref::<Thing>())
                .unwrap()
        )
    }
}
```

**Comment by dandavison** [comment]
In case these notes are helpful to the library API design:

[delta](https://github.com/dandavison/delta) is a project that is using (copying) some code from bat and might be able to avoid this duplication by using bat as a library. Like bat, delta uses syntect for syntax-highlighting and spawns a pager as a child process. I am deliberately making delta quite closely related to bat, for example honoring environment variables `BAT_THEME` and `BAT_PAGER`, and using the same binary syntax/theme blobs. I plan for delta to also be able to read custom themes from the same bat cache dir but haven't implemented that yet. 

All the bat code copied by delta is kept in its own directory: https://github.com/dandavison/delta/tree/master/src/bat

Currently, the bat objects used by delta code are:

1. `assets::{list_languages, HighlightingAssets}`
1. `output::{OutputType, PagingMode}`

In addition, I recently realized that delta is [completely failing](https://github.com/dandavison/delta/issues/54) to honor requests for ansi-light, ansi-dark and base16 themes. This is because I had naively used the bat themes without incorporating the special handling of those themes that was added to bat code in  https://github.com/sharkdp/bat/pull/543. (The bat-as-a-library project might have prevented me from making that mistake.)  So I will probably also be adding the following to the list:

1. `terminal::to_ansi_color`

**Comment by sharkdp** [comment]
Thank you very much for your comments both of you.

I definitely agree that the current `InputFile` struct is not a good design choice for a public API.

Before thinking about the internal implementation, we should think about the few use-cases that we have right now (for `bat` as a library):

* The `bat` command-line application itself
* `delta`
* `cargo-inspect`

Where does the input come from in each of these cases? What kind of metadata can be provided in addition.

For `bat`, we have (as you said):

* code as a string (for theme preview) + hard-coded syntax
* ordinary file + filepath/name (from which the syntax may be extracted) + filepath (from which git changes can be determined)
* standard input. here, the syntax can only be determined from the first line of input

For the latter two, automatic syntax detection can be manually overwritten.

**Comment by eth-p** [comment]
## Sources

**Files:**
- Data (via `Read`)
- Path
- Syntax (by path)
- Changes (by path)

**String:**
- Data
- Syntax (manual/detected)

**Stream:** (e.g. stdin)
- Data (via `Read`)
- Syntax (manual/detected).

## Thoughts

I think we could go for a mixed approach on how to provide this metadata. Fundamental metadata like the file name/path, syntax overrides, and data (using `Read`) should be included with the `Input` struct. Those directly relate to the core functionality of bat, and should provide roughly enough information to infer other kinds of metadata (git changes from the file path) from.

Other metadata like line ranges and changes could be added using the properties API I described in the original comment. That should help decouple expensive features like git changes, which would allow us to move them into their own separate cargo features so consumers of `bat`-as-a-library won't need to depend on libgit2 when all they need is syntax highlighting.

**Comment by sharkdp** [comment]
currently working on this ...

**Comment by sharkdp** [comment]
... see #936
