### ISSUE TITLE
When'll you use bat, instead of `git diff` plus `Vim` plus `less`?

### ISSUE THREAD

**Issue by D3Hunter** [sharkdp/bat#76]
When'll you use `bat`, instead of `git diff` plus `Vim` plus `less`?

i use:
`git diff` for viewing file change with context, i think that's enough.
`vim` for editing and viewing with syntax highlighting
`less` for viewing and searching plain files, specifically `log files`

As of `bat`, i installed and tried it, it's kind of cool but i don't need it in normal work.
what's your thoughts?

**Comment by sharkdp** [comment]
I use it because

- I can save a few keys when I only want to look at a file (as compared to `vim FILE`, `:q<ENTER>`).
- I can easily view multiple files at once (`bat src/*.rs`)
- I like syntax highlighting. Everywhere. Even when reviewing git modifications.
- It has superior syntax-highlighting (as compared to `vim`; this is my current feeling.. I don't have proof).

.. and that's it (for now). People might find other reasons to use it - or they might not. If the existing tools work for you, that's also fine.

**Comment by D3Hunter** [comment]
> I like syntax highlighting. Everywhere. Even when reviewing git modifications.
syntax highlighting would be good when reviewing git modifications, but viewing the whole file is not, i want to focus the part that has changed, specifically when the file is quite long, say handreds of lines.

**Comment by sharkdp** [comment]
Please see #23.
