### ISSUE TITLE
Does not work with `most` pager

### ISSUE THREAD

**Issue by jsumners** [sharkdp/bat#799]
http://www.jedsoft.org/most/

![image](https://user-images.githubusercontent.com/321201/72156459-97e01980-3383-11ea-9868-e98449000939.png)

**Comment by eth-p** [comment]
The junk you're seeing is ANSI escape sequences for 24-bit color. They're showing up directly instead of being properly interpreted because your pager is replacing the ESC char with `^[`.

In order for colors to work with `less`, it needed the `--RAW-CONTROL-CHARS` option to stop it from replacing ESC. You're going to need to add a flag to your `BAT_PAGER` variable to make `most` work with bat.

Based on the manpage for `most` that I found [here](https://linux.die.net/man/1/most), it doesn't seem to support ANSI escape sequence passthrough. But, you might be able to try the `-k` flag?

**Comment by jsumners** [comment]
Nope. Does not work. Probably just plain incompatible. Was simply testing out this tool (bat) and figured I'd make mention of the issue. 🤷‍♂ 

Neat take on `cat`, but most of my usage includes piping into other things so I'll probably continue on with the original.

Thank you for taking the time to investigate.

**Comment by sharkdp** [comment]
> but most of my usage includes piping into other things so I'll probably continue on with the original.

Note that `bat` supports piping to other programs. It will act just like `cat` whenever the output goes to a non-interactive terminal.

**Comment by nixpulvis** [comment]
I would love to be able to use `BAT_PAGER="less -RS"` and invoke `bat` without the need to also provide `--wrap=never` TBH.

**Comment by jsumners** [comment]
@nixpulvis what does that have to do with this closed issue?

**Comment by nixpulvis** [comment]
@jsumners nothing directly. Just didn't know if I should create a new issue, since it's a default and I wouldn't assume you'd want to change it.

**Comment by sharkdp** [comment]
@nixpulvis Please open a new ticket if you think there is a need for it. Before doing that, please make sure that you read the documentation on the configuration file: https://github.com/sharkdp/bat#configuration-file

**Comment by nixpulvis** [comment]
@sharkdp ah perfect, easy config:

```
--wrap=never
--pager="less -SR"
```
