### ISSUE TITLE
Previewing binary files?

### ISSUE THREAD

**Issue by for-coursera** [sharkdp/bat#800]
Some option allowing to get a glimpse of binary files would be great. May be some first N bytes in `hexdump` style as mentioned [here](https://github.com/sharkdp/bat/issues/248), may be just a few lines of the `cat`-like output.

What do you think?

**Comment by eth-p** [comment]
Related to: https://github.com/sharkdp/bat/issues/619

**Comment by for-coursera** [comment]
@eth-p 

Not really. `--show-all` affects the way non-binary files are displayed, too.

**Comment by eth-p** [comment]
It was related to the initial issue of using `hexyl` for hex-dump previews, and I linked it for reference. But yeah, I don't think the resolution for that issue solves this one.

**Comment by desbma** [comment]
It was suggested here https://github.com/sharkdp/bat/issues/619#issuecomment-517395690 that having a `BAT_BINARY_VIEWER` would be an elegant solution to this.

I would also like this to be implemented, because I sometimes use `bat` for example to preview archive content, and because the data is coming from a pipe, I have no way to choose whether to preview it with `bat` or `hexyl`.

`bat -A` changes the output for text files and does not make binary files any more "readable".

So in that case, `BAT_BINARY_VIEWER=hexyl bat` would be perfect.

**Comment by sharkdp** [comment]
I'd rather not implement this. It's easy to write a wrapper script that would do this.

**Comment by SuperSandro2000** [comment]
> I'd rather not implement this. It's easy to write a wrapper script that would do this.

If the exit code would be different from 0. Right now it is just 0 which makes writting a generic wrapper harder.

**Comment by desbma** [comment]
> It's easy to write a wrapper script that would do this.

When reading data from stdin it's definitely not trivial. You'd have to :
* read an arbitrary amount of data from the pipe to guess if it's binary or not, hoping it does end in the middle of an unicode char, and essentially duplicating the detection bat already does
* once you have guessed if its binary or not, you can not just `execvp` to` bat` or `hexyl`, as the data that has already been read would be lost, so you need to create another pipe, write to it the first chunk, and then proxy between the wrapper's stdin and `bat`/`hexyl` 
* handle the SIGCHLD signal
* probably more I forgot

I have written such script, and it is near 100 lines of Python, and very far from handling all corner cases.

It's too bad you don't want to consider a solution for this as you are in a special position to do so as the author of both `bat` and `hexyl`.

**Comment by SuperSandro2000** [comment]
For catting a file it is easier. You can extract the filename, check with isutf8 what it is and then handle it appropriate.

**Comment by xeruf** [comment]
I have written a wrapper script to preview almost anything using bat, ls and some extra tools - hexyl is not integrated yet, but that sounds great, too.
https://git.jfischer.org/xeruf/dotfiles/src/branch/main/.local/bin/scripts/b

I am considering to publish it at some point as I am dazzled to not have found anything like that previously.

**Comment by desbma** [comment]
I also wrote [rsop](https://github.com/desbma/rsop) as general wrapper for terminal tools like bat and hexyl.
The initial motivation was precisely this issue, for example when previewing an archive and not knowing if the data is text or binary. Then it evolved into a complete xdg-open replacement and more.

**Comment by xeruf** [comment]
@desbma Wow I had been searching for such a tool for so long until building it myself, this looks fantastic :) and maybe I can contribute something to it as well

**Comment by desbma** [comment]
Yeah I wrote it for myself with this issue in mind, but now it can do much more than text/binary dispatch because it can sniff MIME type, including when piped, so you can preview images, pcap files, whatever.

You should be able to customize it for your needs with the config file, but if not, contribution welcome!
