### ISSUE TITLE
Highlight Column

### ISSUE THREAD

**Issue by RuRo** [sharkdp/bat#864]
This is a feature request.

Some code styles enforce certain maximum/recommended file width. So I propose adding a 
```
    -C, --highlight-column <N>...       
            Highlight the N-th column with a different background color
```
option, which would act in a similar way to
```
    -H, --highlight-line <N>...       
            Highlight the N-th line with a different background color
```
but would highlight columns instead of rows.

**Comment by sharkdp** [comment]
Thank you for your feedback.

I personally don't see a huge need for this. In a text editor, such a feature makes sense because a user might want to break a line into two if the line becomes too long. In a view-only application however, I don't see an immediate use for highlighting columns.

Note that we have a `--terminal-width <width>` feature in `bat` which might help to spot "code style violations", if that is the desired goal.

**Comment by RuRo** [comment]
Well, obviously, if the intention is to actively check for code style violations, I would fire up my IDE or run the proper linting. But I was thinking more along the lines of "nice to have, always enabled visual guide to ease your mind while reviewing code", rather than "an option that you specifically turn on for checking code style".

Anyway, this was just a small suggestion, not a critical feature, so it's up to you, if you think if it's worth implementing.

P.S. I actually prefer `--wrap=never` and `less -S` to soft wrapping, since it makes potential offenders easier to spot and doesn't mess with automatically generated content with long lines, but thanks for the suggestion anyway.

**Comment by sharkdp** [comment]
I don't see a huge support for this, so I'm going to close this for now.
