### ISSUE TITLE
Why isn't this program called "rat"?

### ISSUE THREAD

**Issue by vitalbone** [sharkdp/bat#886]
A real missed opportunity...

Srsly tho, big fan. Keep up the great work.

**Comment by sharkdp** [comment]
You are not the first to suggest this :-)

see https://www.reddit.com/r/commandline/comments/8fztwa/bat_a_cat1_clone_with_syntax_highlighting_and_git/dy7p3ds?utm_source=share&utm_medium=web2x

Going to quote my answer from back then: *... I thought about it :-). Then I remembered, that some people didn't like the name of my command-line calculator [insect](https://insect.sh/) due to bad associations. Well, not sure if "bat" is much better than "rat" in this respect.*

**Comment by gengjun** [comment]
put this in your .bashrc:
alias rat='batcat'
or
alias rat='bat'
