### ISSUE TITLE
The `--file-name` option behaves inconsistently with displaying git changes.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#999]
![image](https://user-images.githubusercontent.com/32112321/81787090-6738f980-94b5-11ea-93c8-71fb61769258.png)
![image](https://user-images.githubusercontent.com/32112321/81786905-217c3100-94b5-11ea-88fc-5c382984b074.png)

Behavior 1: File via stdin and `--file-name`, doesn't show the changes.  
Behavior 2: File via argument and `--file-name`, shows the changes.
Behavior 3: File via argument and conflicting `--file-name`, still shows the changes for the file.

It would be a good idea to discuss what the intended behavior should be, and fix the cases that don't line up.

**Comment by sharkdp** [comment]
Not that it really matters for this bug, but note that you have to use
```
--map-syntax '*.js:Bourne Again Shell (bash)'
```
to make the syntax mapping work.

**Comment by sharkdp** [comment]
When originally implementing this, I only thought about whether to use the real filename or the provided filename to query Git changes. I chose the real filename (this is why it shows the changes in cases 2 and 3) because I was thinking about the pretty printing use case a la
``` bash
pretty_print path/to/main.js > /tmp/main.pretty.js
bat /tmp/main.pretty.js --file-name path/to/main.js
```
where it doesn't really make sense to get the Git changes for `path/to/main.js` because they wouldn't match with the content of `/tmp/main.pretty.js`. It also doesn't make sense to get the Git changes for `/tmp/main.pretty.js`, as there won't be any. But we can't really solve this for the pretty printing use case.

In scenarios 2 and 3, I think it's fine to show the Git modifications of the original file. The user only gave an alternative file name to display in the header.

I guess you would like to see the changes in scenario 1 as well, but I'm not sure if that's a good idea. We cannot be sure that the Git changes in the `--file-name` path match the content. We can't even be sure if that path is a real path.

In my opinion, this works as intended and I would not consider this a bug.

**Comment by eth-p** [comment]
Those are fair points, and I can agree with your reasoning behind it. I'll close this issue.
